
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `GuildBotConfig` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model GuildBotConfig
 * 
 */
export type GuildBotConfigModel = runtime.Types.Result.DefaultSelection<Prisma.$GuildBotConfigPayload>

export type AggregateGuildBotConfig = {
  _count: GuildBotConfigCountAggregateOutputType | null
  _avg: GuildBotConfigAvgAggregateOutputType | null
  _sum: GuildBotConfigSumAggregateOutputType | null
  _min: GuildBotConfigMinAggregateOutputType | null
  _max: GuildBotConfigMaxAggregateOutputType | null
}

export type GuildBotConfigAvgAggregateOutputType = {
  paperPackPriceCents: number | null
  paperPackSheetCount: number | null
  laminationPackPriceCents: number | null
  laminationPackSheetCount: number | null
  holographicStickerPackPriceCents: number | null
  holographicStickerPackSheetCount: number | null
  cardstockPackPriceCents: number | null
  cardstockPackSheetCount: number | null
}

export type GuildBotConfigSumAggregateOutputType = {
  paperPackPriceCents: number | null
  paperPackSheetCount: number | null
  laminationPackPriceCents: number | null
  laminationPackSheetCount: number | null
  holographicStickerPackPriceCents: number | null
  holographicStickerPackSheetCount: number | null
  cardstockPackPriceCents: number | null
  cardstockPackSheetCount: number | null
}

export type GuildBotConfigMinAggregateOutputType = {
  oid: string | null
  guildId: string | null
  paperPackPriceCents: number | null
  paperPackSheetCount: number | null
  laminationPackPriceCents: number | null
  laminationPackSheetCount: number | null
  holographicStickerPackPriceCents: number | null
  holographicStickerPackSheetCount: number | null
  cardstockPackPriceCents: number | null
  cardstockPackSheetCount: number | null
  photoLaminatedProductionEnabled: boolean | null
  foilCardProductionEnabled: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GuildBotConfigMaxAggregateOutputType = {
  oid: string | null
  guildId: string | null
  paperPackPriceCents: number | null
  paperPackSheetCount: number | null
  laminationPackPriceCents: number | null
  laminationPackSheetCount: number | null
  holographicStickerPackPriceCents: number | null
  holographicStickerPackSheetCount: number | null
  cardstockPackPriceCents: number | null
  cardstockPackSheetCount: number | null
  photoLaminatedProductionEnabled: boolean | null
  foilCardProductionEnabled: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GuildBotConfigCountAggregateOutputType = {
  oid: number
  guildId: number
  paperPackPriceCents: number
  paperPackSheetCount: number
  laminationPackPriceCents: number
  laminationPackSheetCount: number
  holographicStickerPackPriceCents: number
  holographicStickerPackSheetCount: number
  cardstockPackPriceCents: number
  cardstockPackSheetCount: number
  photoLaminatedProductionEnabled: number
  foilCardProductionEnabled: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type GuildBotConfigAvgAggregateInputType = {
  paperPackPriceCents?: true
  paperPackSheetCount?: true
  laminationPackPriceCents?: true
  laminationPackSheetCount?: true
  holographicStickerPackPriceCents?: true
  holographicStickerPackSheetCount?: true
  cardstockPackPriceCents?: true
  cardstockPackSheetCount?: true
}

export type GuildBotConfigSumAggregateInputType = {
  paperPackPriceCents?: true
  paperPackSheetCount?: true
  laminationPackPriceCents?: true
  laminationPackSheetCount?: true
  holographicStickerPackPriceCents?: true
  holographicStickerPackSheetCount?: true
  cardstockPackPriceCents?: true
  cardstockPackSheetCount?: true
}

export type GuildBotConfigMinAggregateInputType = {
  oid?: true
  guildId?: true
  paperPackPriceCents?: true
  paperPackSheetCount?: true
  laminationPackPriceCents?: true
  laminationPackSheetCount?: true
  holographicStickerPackPriceCents?: true
  holographicStickerPackSheetCount?: true
  cardstockPackPriceCents?: true
  cardstockPackSheetCount?: true
  photoLaminatedProductionEnabled?: true
  foilCardProductionEnabled?: true
  createdAt?: true
  updatedAt?: true
}

export type GuildBotConfigMaxAggregateInputType = {
  oid?: true
  guildId?: true
  paperPackPriceCents?: true
  paperPackSheetCount?: true
  laminationPackPriceCents?: true
  laminationPackSheetCount?: true
  holographicStickerPackPriceCents?: true
  holographicStickerPackSheetCount?: true
  cardstockPackPriceCents?: true
  cardstockPackSheetCount?: true
  photoLaminatedProductionEnabled?: true
  foilCardProductionEnabled?: true
  createdAt?: true
  updatedAt?: true
}

export type GuildBotConfigCountAggregateInputType = {
  oid?: true
  guildId?: true
  paperPackPriceCents?: true
  paperPackSheetCount?: true
  laminationPackPriceCents?: true
  laminationPackSheetCount?: true
  holographicStickerPackPriceCents?: true
  holographicStickerPackSheetCount?: true
  cardstockPackPriceCents?: true
  cardstockPackSheetCount?: true
  photoLaminatedProductionEnabled?: true
  foilCardProductionEnabled?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type GuildBotConfigAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GuildBotConfig to aggregate.
   */
  where?: Prisma.GuildBotConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuildBotConfigs to fetch.
   */
  orderBy?: Prisma.GuildBotConfigOrderByWithRelationInput | Prisma.GuildBotConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GuildBotConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuildBotConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuildBotConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GuildBotConfigs
  **/
  _count?: true | GuildBotConfigCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GuildBotConfigAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GuildBotConfigSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GuildBotConfigMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GuildBotConfigMaxAggregateInputType
}

export type GetGuildBotConfigAggregateType<T extends GuildBotConfigAggregateArgs> = {
      [P in keyof T & keyof AggregateGuildBotConfig]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGuildBotConfig[P]>
    : Prisma.GetScalarType<T[P], AggregateGuildBotConfig[P]>
}




export type GuildBotConfigGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GuildBotConfigWhereInput
  orderBy?: Prisma.GuildBotConfigOrderByWithAggregationInput | Prisma.GuildBotConfigOrderByWithAggregationInput[]
  by: Prisma.GuildBotConfigScalarFieldEnum[] | Prisma.GuildBotConfigScalarFieldEnum
  having?: Prisma.GuildBotConfigScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GuildBotConfigCountAggregateInputType | true
  _avg?: GuildBotConfigAvgAggregateInputType
  _sum?: GuildBotConfigSumAggregateInputType
  _min?: GuildBotConfigMinAggregateInputType
  _max?: GuildBotConfigMaxAggregateInputType
}

export type GuildBotConfigGroupByOutputType = {
  oid: string
  guildId: string
  paperPackPriceCents: number | null
  paperPackSheetCount: number | null
  laminationPackPriceCents: number | null
  laminationPackSheetCount: number | null
  holographicStickerPackPriceCents: number | null
  holographicStickerPackSheetCount: number | null
  cardstockPackPriceCents: number | null
  cardstockPackSheetCount: number | null
  photoLaminatedProductionEnabled: boolean | null
  foilCardProductionEnabled: boolean | null
  createdAt: Date
  updatedAt: Date
  _count: GuildBotConfigCountAggregateOutputType | null
  _avg: GuildBotConfigAvgAggregateOutputType | null
  _sum: GuildBotConfigSumAggregateOutputType | null
  _min: GuildBotConfigMinAggregateOutputType | null
  _max: GuildBotConfigMaxAggregateOutputType | null
}

type GetGuildBotConfigGroupByPayload<T extends GuildBotConfigGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GuildBotConfigGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GuildBotConfigGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GuildBotConfigGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GuildBotConfigGroupByOutputType[P]>
      }
    >
  >



export type GuildBotConfigWhereInput = {
  AND?: Prisma.GuildBotConfigWhereInput | Prisma.GuildBotConfigWhereInput[]
  OR?: Prisma.GuildBotConfigWhereInput[]
  NOT?: Prisma.GuildBotConfigWhereInput | Prisma.GuildBotConfigWhereInput[]
  oid?: Prisma.StringFilter<"GuildBotConfig"> | string
  guildId?: Prisma.StringFilter<"GuildBotConfig"> | string
  paperPackPriceCents?: Prisma.IntNullableFilter<"GuildBotConfig"> | number | null
  paperPackSheetCount?: Prisma.IntNullableFilter<"GuildBotConfig"> | number | null
  laminationPackPriceCents?: Prisma.IntNullableFilter<"GuildBotConfig"> | number | null
  laminationPackSheetCount?: Prisma.IntNullableFilter<"GuildBotConfig"> | number | null
  holographicStickerPackPriceCents?: Prisma.IntNullableFilter<"GuildBotConfig"> | number | null
  holographicStickerPackSheetCount?: Prisma.IntNullableFilter<"GuildBotConfig"> | number | null
  cardstockPackPriceCents?: Prisma.IntNullableFilter<"GuildBotConfig"> | number | null
  cardstockPackSheetCount?: Prisma.IntNullableFilter<"GuildBotConfig"> | number | null
  photoLaminatedProductionEnabled?: Prisma.BoolNullableFilter<"GuildBotConfig"> | boolean | null
  foilCardProductionEnabled?: Prisma.BoolNullableFilter<"GuildBotConfig"> | boolean | null
  createdAt?: Prisma.DateTimeFilter<"GuildBotConfig"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GuildBotConfig"> | Date | string
  guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>
}

export type GuildBotConfigOrderByWithRelationInput = {
  oid?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  paperPackPriceCents?: Prisma.SortOrder
  paperPackSheetCount?: Prisma.SortOrder
  laminationPackPriceCents?: Prisma.SortOrder
  laminationPackSheetCount?: Prisma.SortOrder
  holographicStickerPackPriceCents?: Prisma.SortOrder
  holographicStickerPackSheetCount?: Prisma.SortOrder
  cardstockPackPriceCents?: Prisma.SortOrder
  cardstockPackSheetCount?: Prisma.SortOrder
  photoLaminatedProductionEnabled?: Prisma.SortOrder
  foilCardProductionEnabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  guild?: Prisma.GuildOrderByWithRelationInput
}

export type GuildBotConfigWhereUniqueInput = Prisma.AtLeast<{
  oid?: string
  guildId?: string
  AND?: Prisma.GuildBotConfigWhereInput | Prisma.GuildBotConfigWhereInput[]
  OR?: Prisma.GuildBotConfigWhereInput[]
  NOT?: Prisma.GuildBotConfigWhereInput | Prisma.GuildBotConfigWhereInput[]
  paperPackPriceCents?: Prisma.IntNullableFilter<"GuildBotConfig"> | number | null
  paperPackSheetCount?: Prisma.IntNullableFilter<"GuildBotConfig"> | number | null
  laminationPackPriceCents?: Prisma.IntNullableFilter<"GuildBotConfig"> | number | null
  laminationPackSheetCount?: Prisma.IntNullableFilter<"GuildBotConfig"> | number | null
  holographicStickerPackPriceCents?: Prisma.IntNullableFilter<"GuildBotConfig"> | number | null
  holographicStickerPackSheetCount?: Prisma.IntNullableFilter<"GuildBotConfig"> | number | null
  cardstockPackPriceCents?: Prisma.IntNullableFilter<"GuildBotConfig"> | number | null
  cardstockPackSheetCount?: Prisma.IntNullableFilter<"GuildBotConfig"> | number | null
  photoLaminatedProductionEnabled?: Prisma.BoolNullableFilter<"GuildBotConfig"> | boolean | null
  foilCardProductionEnabled?: Prisma.BoolNullableFilter<"GuildBotConfig"> | boolean | null
  createdAt?: Prisma.DateTimeFilter<"GuildBotConfig"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GuildBotConfig"> | Date | string
  guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>
}, "oid" | "guildId">

export type GuildBotConfigOrderByWithAggregationInput = {
  oid?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  paperPackPriceCents?: Prisma.SortOrder
  paperPackSheetCount?: Prisma.SortOrder
  laminationPackPriceCents?: Prisma.SortOrder
  laminationPackSheetCount?: Prisma.SortOrder
  holographicStickerPackPriceCents?: Prisma.SortOrder
  holographicStickerPackSheetCount?: Prisma.SortOrder
  cardstockPackPriceCents?: Prisma.SortOrder
  cardstockPackSheetCount?: Prisma.SortOrder
  photoLaminatedProductionEnabled?: Prisma.SortOrder
  foilCardProductionEnabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.GuildBotConfigCountOrderByAggregateInput
  _avg?: Prisma.GuildBotConfigAvgOrderByAggregateInput
  _max?: Prisma.GuildBotConfigMaxOrderByAggregateInput
  _min?: Prisma.GuildBotConfigMinOrderByAggregateInput
  _sum?: Prisma.GuildBotConfigSumOrderByAggregateInput
}

export type GuildBotConfigScalarWhereWithAggregatesInput = {
  AND?: Prisma.GuildBotConfigScalarWhereWithAggregatesInput | Prisma.GuildBotConfigScalarWhereWithAggregatesInput[]
  OR?: Prisma.GuildBotConfigScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GuildBotConfigScalarWhereWithAggregatesInput | Prisma.GuildBotConfigScalarWhereWithAggregatesInput[]
  oid?: Prisma.StringWithAggregatesFilter<"GuildBotConfig"> | string
  guildId?: Prisma.StringWithAggregatesFilter<"GuildBotConfig"> | string
  paperPackPriceCents?: Prisma.IntNullableWithAggregatesFilter<"GuildBotConfig"> | number | null
  paperPackSheetCount?: Prisma.IntNullableWithAggregatesFilter<"GuildBotConfig"> | number | null
  laminationPackPriceCents?: Prisma.IntNullableWithAggregatesFilter<"GuildBotConfig"> | number | null
  laminationPackSheetCount?: Prisma.IntNullableWithAggregatesFilter<"GuildBotConfig"> | number | null
  holographicStickerPackPriceCents?: Prisma.IntNullableWithAggregatesFilter<"GuildBotConfig"> | number | null
  holographicStickerPackSheetCount?: Prisma.IntNullableWithAggregatesFilter<"GuildBotConfig"> | number | null
  cardstockPackPriceCents?: Prisma.IntNullableWithAggregatesFilter<"GuildBotConfig"> | number | null
  cardstockPackSheetCount?: Prisma.IntNullableWithAggregatesFilter<"GuildBotConfig"> | number | null
  photoLaminatedProductionEnabled?: Prisma.BoolNullableWithAggregatesFilter<"GuildBotConfig"> | boolean | null
  foilCardProductionEnabled?: Prisma.BoolNullableWithAggregatesFilter<"GuildBotConfig"> | boolean | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"GuildBotConfig"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"GuildBotConfig"> | Date | string
}

export type GuildBotConfigCreateInput = {
  oid?: string
  paperPackPriceCents?: number | null
  paperPackSheetCount?: number | null
  laminationPackPriceCents?: number | null
  laminationPackSheetCount?: number | null
  holographicStickerPackPriceCents?: number | null
  holographicStickerPackSheetCount?: number | null
  cardstockPackPriceCents?: number | null
  cardstockPackSheetCount?: number | null
  photoLaminatedProductionEnabled?: boolean | null
  foilCardProductionEnabled?: boolean | null
  createdAt?: Date | string
  updatedAt?: Date | string
  guild: Prisma.GuildCreateNestedOneWithoutBotConfigInput
}

export type GuildBotConfigUncheckedCreateInput = {
  oid?: string
  guildId: string
  paperPackPriceCents?: number | null
  paperPackSheetCount?: number | null
  laminationPackPriceCents?: number | null
  laminationPackSheetCount?: number | null
  holographicStickerPackPriceCents?: number | null
  holographicStickerPackSheetCount?: number | null
  cardstockPackPriceCents?: number | null
  cardstockPackSheetCount?: number | null
  photoLaminatedProductionEnabled?: boolean | null
  foilCardProductionEnabled?: boolean | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GuildBotConfigUpdateInput = {
  paperPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  paperPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  laminationPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  laminationPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  holographicStickerPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  holographicStickerPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cardstockPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cardstockPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  photoLaminatedProductionEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  foilCardProductionEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  guild?: Prisma.GuildUpdateOneRequiredWithoutBotConfigNestedInput
}

export type GuildBotConfigUncheckedUpdateInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  paperPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  paperPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  laminationPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  laminationPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  holographicStickerPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  holographicStickerPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cardstockPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cardstockPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  photoLaminatedProductionEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  foilCardProductionEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GuildBotConfigCreateManyInput = {
  oid?: string
  guildId: string
  paperPackPriceCents?: number | null
  paperPackSheetCount?: number | null
  laminationPackPriceCents?: number | null
  laminationPackSheetCount?: number | null
  holographicStickerPackPriceCents?: number | null
  holographicStickerPackSheetCount?: number | null
  cardstockPackPriceCents?: number | null
  cardstockPackSheetCount?: number | null
  photoLaminatedProductionEnabled?: boolean | null
  foilCardProductionEnabled?: boolean | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GuildBotConfigUpdateManyMutationInput = {
  paperPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  paperPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  laminationPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  laminationPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  holographicStickerPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  holographicStickerPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cardstockPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cardstockPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  photoLaminatedProductionEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  foilCardProductionEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GuildBotConfigUncheckedUpdateManyInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  paperPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  paperPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  laminationPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  laminationPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  holographicStickerPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  holographicStickerPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cardstockPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cardstockPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  photoLaminatedProductionEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  foilCardProductionEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GuildBotConfigNullableScalarRelationFilter = {
  is?: Prisma.GuildBotConfigWhereInput | null
  isNot?: Prisma.GuildBotConfigWhereInput | null
}

export type GuildBotConfigCountOrderByAggregateInput = {
  oid?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  paperPackPriceCents?: Prisma.SortOrder
  paperPackSheetCount?: Prisma.SortOrder
  laminationPackPriceCents?: Prisma.SortOrder
  laminationPackSheetCount?: Prisma.SortOrder
  holographicStickerPackPriceCents?: Prisma.SortOrder
  holographicStickerPackSheetCount?: Prisma.SortOrder
  cardstockPackPriceCents?: Prisma.SortOrder
  cardstockPackSheetCount?: Prisma.SortOrder
  photoLaminatedProductionEnabled?: Prisma.SortOrder
  foilCardProductionEnabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GuildBotConfigAvgOrderByAggregateInput = {
  paperPackPriceCents?: Prisma.SortOrder
  paperPackSheetCount?: Prisma.SortOrder
  laminationPackPriceCents?: Prisma.SortOrder
  laminationPackSheetCount?: Prisma.SortOrder
  holographicStickerPackPriceCents?: Prisma.SortOrder
  holographicStickerPackSheetCount?: Prisma.SortOrder
  cardstockPackPriceCents?: Prisma.SortOrder
  cardstockPackSheetCount?: Prisma.SortOrder
}

export type GuildBotConfigMaxOrderByAggregateInput = {
  oid?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  paperPackPriceCents?: Prisma.SortOrder
  paperPackSheetCount?: Prisma.SortOrder
  laminationPackPriceCents?: Prisma.SortOrder
  laminationPackSheetCount?: Prisma.SortOrder
  holographicStickerPackPriceCents?: Prisma.SortOrder
  holographicStickerPackSheetCount?: Prisma.SortOrder
  cardstockPackPriceCents?: Prisma.SortOrder
  cardstockPackSheetCount?: Prisma.SortOrder
  photoLaminatedProductionEnabled?: Prisma.SortOrder
  foilCardProductionEnabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GuildBotConfigMinOrderByAggregateInput = {
  oid?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  paperPackPriceCents?: Prisma.SortOrder
  paperPackSheetCount?: Prisma.SortOrder
  laminationPackPriceCents?: Prisma.SortOrder
  laminationPackSheetCount?: Prisma.SortOrder
  holographicStickerPackPriceCents?: Prisma.SortOrder
  holographicStickerPackSheetCount?: Prisma.SortOrder
  cardstockPackPriceCents?: Prisma.SortOrder
  cardstockPackSheetCount?: Prisma.SortOrder
  photoLaminatedProductionEnabled?: Prisma.SortOrder
  foilCardProductionEnabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GuildBotConfigSumOrderByAggregateInput = {
  paperPackPriceCents?: Prisma.SortOrder
  paperPackSheetCount?: Prisma.SortOrder
  laminationPackPriceCents?: Prisma.SortOrder
  laminationPackSheetCount?: Prisma.SortOrder
  holographicStickerPackPriceCents?: Prisma.SortOrder
  holographicStickerPackSheetCount?: Prisma.SortOrder
  cardstockPackPriceCents?: Prisma.SortOrder
  cardstockPackSheetCount?: Prisma.SortOrder
}

export type GuildBotConfigCreateNestedOneWithoutGuildInput = {
  create?: Prisma.XOR<Prisma.GuildBotConfigCreateWithoutGuildInput, Prisma.GuildBotConfigUncheckedCreateWithoutGuildInput>
  connectOrCreate?: Prisma.GuildBotConfigCreateOrConnectWithoutGuildInput
  connect?: Prisma.GuildBotConfigWhereUniqueInput
}

export type GuildBotConfigUncheckedCreateNestedOneWithoutGuildInput = {
  create?: Prisma.XOR<Prisma.GuildBotConfigCreateWithoutGuildInput, Prisma.GuildBotConfigUncheckedCreateWithoutGuildInput>
  connectOrCreate?: Prisma.GuildBotConfigCreateOrConnectWithoutGuildInput
  connect?: Prisma.GuildBotConfigWhereUniqueInput
}

export type GuildBotConfigUpdateOneWithoutGuildNestedInput = {
  create?: Prisma.XOR<Prisma.GuildBotConfigCreateWithoutGuildInput, Prisma.GuildBotConfigUncheckedCreateWithoutGuildInput>
  connectOrCreate?: Prisma.GuildBotConfigCreateOrConnectWithoutGuildInput
  upsert?: Prisma.GuildBotConfigUpsertWithoutGuildInput
  disconnect?: Prisma.GuildBotConfigWhereInput | boolean
  delete?: Prisma.GuildBotConfigWhereInput | boolean
  connect?: Prisma.GuildBotConfigWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GuildBotConfigUpdateToOneWithWhereWithoutGuildInput, Prisma.GuildBotConfigUpdateWithoutGuildInput>, Prisma.GuildBotConfigUncheckedUpdateWithoutGuildInput>
}

export type GuildBotConfigUncheckedUpdateOneWithoutGuildNestedInput = {
  create?: Prisma.XOR<Prisma.GuildBotConfigCreateWithoutGuildInput, Prisma.GuildBotConfigUncheckedCreateWithoutGuildInput>
  connectOrCreate?: Prisma.GuildBotConfigCreateOrConnectWithoutGuildInput
  upsert?: Prisma.GuildBotConfigUpsertWithoutGuildInput
  disconnect?: Prisma.GuildBotConfigWhereInput | boolean
  delete?: Prisma.GuildBotConfigWhereInput | boolean
  connect?: Prisma.GuildBotConfigWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GuildBotConfigUpdateToOneWithWhereWithoutGuildInput, Prisma.GuildBotConfigUpdateWithoutGuildInput>, Prisma.GuildBotConfigUncheckedUpdateWithoutGuildInput>
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
  unset?: boolean
}

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null
  unset?: boolean
}

export type GuildBotConfigCreateWithoutGuildInput = {
  oid?: string
  paperPackPriceCents?: number | null
  paperPackSheetCount?: number | null
  laminationPackPriceCents?: number | null
  laminationPackSheetCount?: number | null
  holographicStickerPackPriceCents?: number | null
  holographicStickerPackSheetCount?: number | null
  cardstockPackPriceCents?: number | null
  cardstockPackSheetCount?: number | null
  photoLaminatedProductionEnabled?: boolean | null
  foilCardProductionEnabled?: boolean | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GuildBotConfigUncheckedCreateWithoutGuildInput = {
  oid?: string
  paperPackPriceCents?: number | null
  paperPackSheetCount?: number | null
  laminationPackPriceCents?: number | null
  laminationPackSheetCount?: number | null
  holographicStickerPackPriceCents?: number | null
  holographicStickerPackSheetCount?: number | null
  cardstockPackPriceCents?: number | null
  cardstockPackSheetCount?: number | null
  photoLaminatedProductionEnabled?: boolean | null
  foilCardProductionEnabled?: boolean | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GuildBotConfigCreateOrConnectWithoutGuildInput = {
  where: Prisma.GuildBotConfigWhereUniqueInput
  create: Prisma.XOR<Prisma.GuildBotConfigCreateWithoutGuildInput, Prisma.GuildBotConfigUncheckedCreateWithoutGuildInput>
}

export type GuildBotConfigUpsertWithoutGuildInput = {
  update: Prisma.XOR<Prisma.GuildBotConfigUpdateWithoutGuildInput, Prisma.GuildBotConfigUncheckedUpdateWithoutGuildInput>
  create: Prisma.XOR<Prisma.GuildBotConfigCreateWithoutGuildInput, Prisma.GuildBotConfigUncheckedCreateWithoutGuildInput>
  where?: Prisma.GuildBotConfigWhereInput
}

export type GuildBotConfigUpdateToOneWithWhereWithoutGuildInput = {
  where?: Prisma.GuildBotConfigWhereInput
  data: Prisma.XOR<Prisma.GuildBotConfigUpdateWithoutGuildInput, Prisma.GuildBotConfigUncheckedUpdateWithoutGuildInput>
}

export type GuildBotConfigUpdateWithoutGuildInput = {
  paperPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  paperPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  laminationPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  laminationPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  holographicStickerPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  holographicStickerPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cardstockPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cardstockPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  photoLaminatedProductionEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  foilCardProductionEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GuildBotConfigUncheckedUpdateWithoutGuildInput = {
  paperPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  paperPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  laminationPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  laminationPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  holographicStickerPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  holographicStickerPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cardstockPackPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cardstockPackSheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  photoLaminatedProductionEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  foilCardProductionEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type GuildBotConfigSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  oid?: boolean
  guildId?: boolean
  paperPackPriceCents?: boolean
  paperPackSheetCount?: boolean
  laminationPackPriceCents?: boolean
  laminationPackSheetCount?: boolean
  holographicStickerPackPriceCents?: boolean
  holographicStickerPackSheetCount?: boolean
  cardstockPackPriceCents?: boolean
  cardstockPackSheetCount?: boolean
  photoLaminatedProductionEnabled?: boolean
  foilCardProductionEnabled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
}, ExtArgs["result"]["guildBotConfig"]>



export type GuildBotConfigSelectScalar = {
  oid?: boolean
  guildId?: boolean
  paperPackPriceCents?: boolean
  paperPackSheetCount?: boolean
  laminationPackPriceCents?: boolean
  laminationPackSheetCount?: boolean
  holographicStickerPackPriceCents?: boolean
  holographicStickerPackSheetCount?: boolean
  cardstockPackPriceCents?: boolean
  cardstockPackSheetCount?: boolean
  photoLaminatedProductionEnabled?: boolean
  foilCardProductionEnabled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type GuildBotConfigOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"oid" | "guildId" | "paperPackPriceCents" | "paperPackSheetCount" | "laminationPackPriceCents" | "laminationPackSheetCount" | "holographicStickerPackPriceCents" | "holographicStickerPackSheetCount" | "cardstockPackPriceCents" | "cardstockPackSheetCount" | "photoLaminatedProductionEnabled" | "foilCardProductionEnabled" | "createdAt" | "updatedAt", ExtArgs["result"]["guildBotConfig"]>
export type GuildBotConfigInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
}

export type $GuildBotConfigPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GuildBotConfig"
  objects: {
    guild: Prisma.$GuildPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    oid: string
    guildId: string
    paperPackPriceCents: number | null
    paperPackSheetCount: number | null
    laminationPackPriceCents: number | null
    laminationPackSheetCount: number | null
    holographicStickerPackPriceCents: number | null
    holographicStickerPackSheetCount: number | null
    cardstockPackPriceCents: number | null
    cardstockPackSheetCount: number | null
    photoLaminatedProductionEnabled: boolean | null
    foilCardProductionEnabled: boolean | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["guildBotConfig"]>
  composites: {}
}

export type GuildBotConfigGetPayload<S extends boolean | null | undefined | GuildBotConfigDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GuildBotConfigPayload, S>

export type GuildBotConfigCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GuildBotConfigFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GuildBotConfigCountAggregateInputType | true
  }

export interface GuildBotConfigDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GuildBotConfig'], meta: { name: 'GuildBotConfig' } }
  /**
   * Find zero or one GuildBotConfig that matches the filter.
   * @param {GuildBotConfigFindUniqueArgs} args - Arguments to find a GuildBotConfig
   * @example
   * // Get one GuildBotConfig
   * const guildBotConfig = await prisma.guildBotConfig.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GuildBotConfigFindUniqueArgs>(args: Prisma.SelectSubset<T, GuildBotConfigFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GuildBotConfigClient<runtime.Types.Result.GetResult<Prisma.$GuildBotConfigPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GuildBotConfig that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GuildBotConfigFindUniqueOrThrowArgs} args - Arguments to find a GuildBotConfig
   * @example
   * // Get one GuildBotConfig
   * const guildBotConfig = await prisma.guildBotConfig.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GuildBotConfigFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GuildBotConfigFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GuildBotConfigClient<runtime.Types.Result.GetResult<Prisma.$GuildBotConfigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GuildBotConfig that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildBotConfigFindFirstArgs} args - Arguments to find a GuildBotConfig
   * @example
   * // Get one GuildBotConfig
   * const guildBotConfig = await prisma.guildBotConfig.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GuildBotConfigFindFirstArgs>(args?: Prisma.SelectSubset<T, GuildBotConfigFindFirstArgs<ExtArgs>>): Prisma.Prisma__GuildBotConfigClient<runtime.Types.Result.GetResult<Prisma.$GuildBotConfigPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GuildBotConfig that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildBotConfigFindFirstOrThrowArgs} args - Arguments to find a GuildBotConfig
   * @example
   * // Get one GuildBotConfig
   * const guildBotConfig = await prisma.guildBotConfig.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GuildBotConfigFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GuildBotConfigFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GuildBotConfigClient<runtime.Types.Result.GetResult<Prisma.$GuildBotConfigPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GuildBotConfigs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildBotConfigFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GuildBotConfigs
   * const guildBotConfigs = await prisma.guildBotConfig.findMany()
   * 
   * // Get first 10 GuildBotConfigs
   * const guildBotConfigs = await prisma.guildBotConfig.findMany({ take: 10 })
   * 
   * // Only select the `oid`
   * const guildBotConfigWithOidOnly = await prisma.guildBotConfig.findMany({ select: { oid: true } })
   * 
   */
  findMany<T extends GuildBotConfigFindManyArgs>(args?: Prisma.SelectSubset<T, GuildBotConfigFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuildBotConfigPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GuildBotConfig.
   * @param {GuildBotConfigCreateArgs} args - Arguments to create a GuildBotConfig.
   * @example
   * // Create one GuildBotConfig
   * const GuildBotConfig = await prisma.guildBotConfig.create({
   *   data: {
   *     // ... data to create a GuildBotConfig
   *   }
   * })
   * 
   */
  create<T extends GuildBotConfigCreateArgs>(args: Prisma.SelectSubset<T, GuildBotConfigCreateArgs<ExtArgs>>): Prisma.Prisma__GuildBotConfigClient<runtime.Types.Result.GetResult<Prisma.$GuildBotConfigPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GuildBotConfigs.
   * @param {GuildBotConfigCreateManyArgs} args - Arguments to create many GuildBotConfigs.
   * @example
   * // Create many GuildBotConfigs
   * const guildBotConfig = await prisma.guildBotConfig.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GuildBotConfigCreateManyArgs>(args?: Prisma.SelectSubset<T, GuildBotConfigCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a GuildBotConfig.
   * @param {GuildBotConfigDeleteArgs} args - Arguments to delete one GuildBotConfig.
   * @example
   * // Delete one GuildBotConfig
   * const GuildBotConfig = await prisma.guildBotConfig.delete({
   *   where: {
   *     // ... filter to delete one GuildBotConfig
   *   }
   * })
   * 
   */
  delete<T extends GuildBotConfigDeleteArgs>(args: Prisma.SelectSubset<T, GuildBotConfigDeleteArgs<ExtArgs>>): Prisma.Prisma__GuildBotConfigClient<runtime.Types.Result.GetResult<Prisma.$GuildBotConfigPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GuildBotConfig.
   * @param {GuildBotConfigUpdateArgs} args - Arguments to update one GuildBotConfig.
   * @example
   * // Update one GuildBotConfig
   * const guildBotConfig = await prisma.guildBotConfig.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GuildBotConfigUpdateArgs>(args: Prisma.SelectSubset<T, GuildBotConfigUpdateArgs<ExtArgs>>): Prisma.Prisma__GuildBotConfigClient<runtime.Types.Result.GetResult<Prisma.$GuildBotConfigPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GuildBotConfigs.
   * @param {GuildBotConfigDeleteManyArgs} args - Arguments to filter GuildBotConfigs to delete.
   * @example
   * // Delete a few GuildBotConfigs
   * const { count } = await prisma.guildBotConfig.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GuildBotConfigDeleteManyArgs>(args?: Prisma.SelectSubset<T, GuildBotConfigDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GuildBotConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildBotConfigUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GuildBotConfigs
   * const guildBotConfig = await prisma.guildBotConfig.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GuildBotConfigUpdateManyArgs>(args: Prisma.SelectSubset<T, GuildBotConfigUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one GuildBotConfig.
   * @param {GuildBotConfigUpsertArgs} args - Arguments to update or create a GuildBotConfig.
   * @example
   * // Update or create a GuildBotConfig
   * const guildBotConfig = await prisma.guildBotConfig.upsert({
   *   create: {
   *     // ... data to create a GuildBotConfig
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GuildBotConfig we want to update
   *   }
   * })
   */
  upsert<T extends GuildBotConfigUpsertArgs>(args: Prisma.SelectSubset<T, GuildBotConfigUpsertArgs<ExtArgs>>): Prisma.Prisma__GuildBotConfigClient<runtime.Types.Result.GetResult<Prisma.$GuildBotConfigPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GuildBotConfigs that matches the filter.
   * @param {GuildBotConfigFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const guildBotConfig = await prisma.guildBotConfig.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.GuildBotConfigFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>

  /**
   * Perform aggregation operations on a GuildBotConfig.
   * @param {GuildBotConfigAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const guildBotConfig = await prisma.guildBotConfig.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.GuildBotConfigAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>


  /**
   * Count the number of GuildBotConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildBotConfigCountArgs} args - Arguments to filter GuildBotConfigs to count.
   * @example
   * // Count the number of GuildBotConfigs
   * const count = await prisma.guildBotConfig.count({
   *   where: {
   *     // ... the filter for the GuildBotConfigs we want to count
   *   }
   * })
  **/
  count<T extends GuildBotConfigCountArgs>(
    args?: Prisma.Subset<T, GuildBotConfigCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GuildBotConfigCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GuildBotConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildBotConfigAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GuildBotConfigAggregateArgs>(args: Prisma.Subset<T, GuildBotConfigAggregateArgs>): Prisma.PrismaPromise<GetGuildBotConfigAggregateType<T>>

  /**
   * Group by GuildBotConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildBotConfigGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GuildBotConfigGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GuildBotConfigGroupByArgs['orderBy'] }
      : { orderBy?: GuildBotConfigGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GuildBotConfigGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGuildBotConfigGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GuildBotConfig model
 */
readonly fields: GuildBotConfigFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GuildBotConfig.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GuildBotConfigClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  guild<T extends Prisma.GuildDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GuildDefaultArgs<ExtArgs>>): Prisma.Prisma__GuildClient<runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GuildBotConfig model
 */
export interface GuildBotConfigFieldRefs {
  readonly oid: Prisma.FieldRef<"GuildBotConfig", 'String'>
  readonly guildId: Prisma.FieldRef<"GuildBotConfig", 'String'>
  readonly paperPackPriceCents: Prisma.FieldRef<"GuildBotConfig", 'Int'>
  readonly paperPackSheetCount: Prisma.FieldRef<"GuildBotConfig", 'Int'>
  readonly laminationPackPriceCents: Prisma.FieldRef<"GuildBotConfig", 'Int'>
  readonly laminationPackSheetCount: Prisma.FieldRef<"GuildBotConfig", 'Int'>
  readonly holographicStickerPackPriceCents: Prisma.FieldRef<"GuildBotConfig", 'Int'>
  readonly holographicStickerPackSheetCount: Prisma.FieldRef<"GuildBotConfig", 'Int'>
  readonly cardstockPackPriceCents: Prisma.FieldRef<"GuildBotConfig", 'Int'>
  readonly cardstockPackSheetCount: Prisma.FieldRef<"GuildBotConfig", 'Int'>
  readonly photoLaminatedProductionEnabled: Prisma.FieldRef<"GuildBotConfig", 'Boolean'>
  readonly foilCardProductionEnabled: Prisma.FieldRef<"GuildBotConfig", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"GuildBotConfig", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"GuildBotConfig", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GuildBotConfig findUnique
 */
export type GuildBotConfigFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildBotConfig
   */
  select?: Prisma.GuildBotConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildBotConfig
   */
  omit?: Prisma.GuildBotConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildBotConfigInclude<ExtArgs> | null
  /**
   * Filter, which GuildBotConfig to fetch.
   */
  where: Prisma.GuildBotConfigWhereUniqueInput
}

/**
 * GuildBotConfig findUniqueOrThrow
 */
export type GuildBotConfigFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildBotConfig
   */
  select?: Prisma.GuildBotConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildBotConfig
   */
  omit?: Prisma.GuildBotConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildBotConfigInclude<ExtArgs> | null
  /**
   * Filter, which GuildBotConfig to fetch.
   */
  where: Prisma.GuildBotConfigWhereUniqueInput
}

/**
 * GuildBotConfig findFirst
 */
export type GuildBotConfigFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildBotConfig
   */
  select?: Prisma.GuildBotConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildBotConfig
   */
  omit?: Prisma.GuildBotConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildBotConfigInclude<ExtArgs> | null
  /**
   * Filter, which GuildBotConfig to fetch.
   */
  where?: Prisma.GuildBotConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuildBotConfigs to fetch.
   */
  orderBy?: Prisma.GuildBotConfigOrderByWithRelationInput | Prisma.GuildBotConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GuildBotConfigs.
   */
  cursor?: Prisma.GuildBotConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuildBotConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuildBotConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GuildBotConfigs.
   */
  distinct?: Prisma.GuildBotConfigScalarFieldEnum | Prisma.GuildBotConfigScalarFieldEnum[]
}

/**
 * GuildBotConfig findFirstOrThrow
 */
export type GuildBotConfigFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildBotConfig
   */
  select?: Prisma.GuildBotConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildBotConfig
   */
  omit?: Prisma.GuildBotConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildBotConfigInclude<ExtArgs> | null
  /**
   * Filter, which GuildBotConfig to fetch.
   */
  where?: Prisma.GuildBotConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuildBotConfigs to fetch.
   */
  orderBy?: Prisma.GuildBotConfigOrderByWithRelationInput | Prisma.GuildBotConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GuildBotConfigs.
   */
  cursor?: Prisma.GuildBotConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuildBotConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuildBotConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GuildBotConfigs.
   */
  distinct?: Prisma.GuildBotConfigScalarFieldEnum | Prisma.GuildBotConfigScalarFieldEnum[]
}

/**
 * GuildBotConfig findMany
 */
export type GuildBotConfigFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildBotConfig
   */
  select?: Prisma.GuildBotConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildBotConfig
   */
  omit?: Prisma.GuildBotConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildBotConfigInclude<ExtArgs> | null
  /**
   * Filter, which GuildBotConfigs to fetch.
   */
  where?: Prisma.GuildBotConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuildBotConfigs to fetch.
   */
  orderBy?: Prisma.GuildBotConfigOrderByWithRelationInput | Prisma.GuildBotConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GuildBotConfigs.
   */
  cursor?: Prisma.GuildBotConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuildBotConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuildBotConfigs.
   */
  skip?: number
  distinct?: Prisma.GuildBotConfigScalarFieldEnum | Prisma.GuildBotConfigScalarFieldEnum[]
}

/**
 * GuildBotConfig create
 */
export type GuildBotConfigCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildBotConfig
   */
  select?: Prisma.GuildBotConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildBotConfig
   */
  omit?: Prisma.GuildBotConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildBotConfigInclude<ExtArgs> | null
  /**
   * The data needed to create a GuildBotConfig.
   */
  data: Prisma.XOR<Prisma.GuildBotConfigCreateInput, Prisma.GuildBotConfigUncheckedCreateInput>
}

/**
 * GuildBotConfig createMany
 */
export type GuildBotConfigCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GuildBotConfigs.
   */
  data: Prisma.GuildBotConfigCreateManyInput | Prisma.GuildBotConfigCreateManyInput[]
}

/**
 * GuildBotConfig update
 */
export type GuildBotConfigUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildBotConfig
   */
  select?: Prisma.GuildBotConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildBotConfig
   */
  omit?: Prisma.GuildBotConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildBotConfigInclude<ExtArgs> | null
  /**
   * The data needed to update a GuildBotConfig.
   */
  data: Prisma.XOR<Prisma.GuildBotConfigUpdateInput, Prisma.GuildBotConfigUncheckedUpdateInput>
  /**
   * Choose, which GuildBotConfig to update.
   */
  where: Prisma.GuildBotConfigWhereUniqueInput
}

/**
 * GuildBotConfig updateMany
 */
export type GuildBotConfigUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GuildBotConfigs.
   */
  data: Prisma.XOR<Prisma.GuildBotConfigUpdateManyMutationInput, Prisma.GuildBotConfigUncheckedUpdateManyInput>
  /**
   * Filter which GuildBotConfigs to update
   */
  where?: Prisma.GuildBotConfigWhereInput
  /**
   * Limit how many GuildBotConfigs to update.
   */
  limit?: number
}

/**
 * GuildBotConfig upsert
 */
export type GuildBotConfigUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildBotConfig
   */
  select?: Prisma.GuildBotConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildBotConfig
   */
  omit?: Prisma.GuildBotConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildBotConfigInclude<ExtArgs> | null
  /**
   * The filter to search for the GuildBotConfig to update in case it exists.
   */
  where: Prisma.GuildBotConfigWhereUniqueInput
  /**
   * In case the GuildBotConfig found by the `where` argument doesn't exist, create a new GuildBotConfig with this data.
   */
  create: Prisma.XOR<Prisma.GuildBotConfigCreateInput, Prisma.GuildBotConfigUncheckedCreateInput>
  /**
   * In case the GuildBotConfig was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GuildBotConfigUpdateInput, Prisma.GuildBotConfigUncheckedUpdateInput>
}

/**
 * GuildBotConfig delete
 */
export type GuildBotConfigDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildBotConfig
   */
  select?: Prisma.GuildBotConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildBotConfig
   */
  omit?: Prisma.GuildBotConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildBotConfigInclude<ExtArgs> | null
  /**
   * Filter which GuildBotConfig to delete.
   */
  where: Prisma.GuildBotConfigWhereUniqueInput
}

/**
 * GuildBotConfig deleteMany
 */
export type GuildBotConfigDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GuildBotConfigs to delete
   */
  where?: Prisma.GuildBotConfigWhereInput
  /**
   * Limit how many GuildBotConfigs to delete.
   */
  limit?: number
}

/**
 * GuildBotConfig findRaw
 */
export type GuildBotConfigFindRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * GuildBotConfig aggregateRaw
 */
export type GuildBotConfigAggregateRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[]
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * GuildBotConfig without action
 */
export type GuildBotConfigDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildBotConfig
   */
  select?: Prisma.GuildBotConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildBotConfig
   */
  omit?: Prisma.GuildBotConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildBotConfigInclude<ExtArgs> | null
}
