
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `PriceConfig` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model PriceConfig
 * 
 */
export type PriceConfigModel = runtime.Types.Result.DefaultSelection<Prisma.$PriceConfigPayload>

export type AggregatePriceConfig = {
  _count: PriceConfigCountAggregateOutputType | null
  _avg: PriceConfigAvgAggregateOutputType | null
  _sum: PriceConfigSumAggregateOutputType | null
  _min: PriceConfigMinAggregateOutputType | null
  _max: PriceConfigMaxAggregateOutputType | null
}

export type PriceConfigAvgAggregateOutputType = {
  id: number | null
  pricePerSheet: number | null
  inkCost: number | null
  laminationCost: number | null
  deckboxPrice: number | null
  sleevesPrice: number | null
}

export type PriceConfigSumAggregateOutputType = {
  id: number | null
  pricePerSheet: number | null
  inkCost: number | null
  laminationCost: number | null
  deckboxPrice: number | null
  sleevesPrice: number | null
}

export type PriceConfigMinAggregateOutputType = {
  id: number | null
  pricePerSheet: number | null
  inkCost: number | null
  laminationCost: number | null
  deckboxPrice: number | null
  sleevesPrice: number | null
  updatedAt: Date | null
}

export type PriceConfigMaxAggregateOutputType = {
  id: number | null
  pricePerSheet: number | null
  inkCost: number | null
  laminationCost: number | null
  deckboxPrice: number | null
  sleevesPrice: number | null
  updatedAt: Date | null
}

export type PriceConfigCountAggregateOutputType = {
  id: number
  pricePerSheet: number
  inkCost: number
  laminationCost: number
  deckboxPrice: number
  sleevesPrice: number
  updatedAt: number
  _all: number
}


export type PriceConfigAvgAggregateInputType = {
  id?: true
  pricePerSheet?: true
  inkCost?: true
  laminationCost?: true
  deckboxPrice?: true
  sleevesPrice?: true
}

export type PriceConfigSumAggregateInputType = {
  id?: true
  pricePerSheet?: true
  inkCost?: true
  laminationCost?: true
  deckboxPrice?: true
  sleevesPrice?: true
}

export type PriceConfigMinAggregateInputType = {
  id?: true
  pricePerSheet?: true
  inkCost?: true
  laminationCost?: true
  deckboxPrice?: true
  sleevesPrice?: true
  updatedAt?: true
}

export type PriceConfigMaxAggregateInputType = {
  id?: true
  pricePerSheet?: true
  inkCost?: true
  laminationCost?: true
  deckboxPrice?: true
  sleevesPrice?: true
  updatedAt?: true
}

export type PriceConfigCountAggregateInputType = {
  id?: true
  pricePerSheet?: true
  inkCost?: true
  laminationCost?: true
  deckboxPrice?: true
  sleevesPrice?: true
  updatedAt?: true
  _all?: true
}

export type PriceConfigAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PriceConfig to aggregate.
   */
  where?: Prisma.PriceConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PriceConfigs to fetch.
   */
  orderBy?: Prisma.PriceConfigOrderByWithRelationInput | Prisma.PriceConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PriceConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PriceConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PriceConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PriceConfigs
  **/
  _count?: true | PriceConfigCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PriceConfigAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PriceConfigSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PriceConfigMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PriceConfigMaxAggregateInputType
}

export type GetPriceConfigAggregateType<T extends PriceConfigAggregateArgs> = {
      [P in keyof T & keyof AggregatePriceConfig]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePriceConfig[P]>
    : Prisma.GetScalarType<T[P], AggregatePriceConfig[P]>
}




export type PriceConfigGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PriceConfigWhereInput
  orderBy?: Prisma.PriceConfigOrderByWithAggregationInput | Prisma.PriceConfigOrderByWithAggregationInput[]
  by: Prisma.PriceConfigScalarFieldEnum[] | Prisma.PriceConfigScalarFieldEnum
  having?: Prisma.PriceConfigScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PriceConfigCountAggregateInputType | true
  _avg?: PriceConfigAvgAggregateInputType
  _sum?: PriceConfigSumAggregateInputType
  _min?: PriceConfigMinAggregateInputType
  _max?: PriceConfigMaxAggregateInputType
}

export type PriceConfigGroupByOutputType = {
  id: number
  pricePerSheet: number
  inkCost: number
  laminationCost: number
  deckboxPrice: number
  sleevesPrice: number
  updatedAt: Date
  _count: PriceConfigCountAggregateOutputType | null
  _avg: PriceConfigAvgAggregateOutputType | null
  _sum: PriceConfigSumAggregateOutputType | null
  _min: PriceConfigMinAggregateOutputType | null
  _max: PriceConfigMaxAggregateOutputType | null
}

type GetPriceConfigGroupByPayload<T extends PriceConfigGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PriceConfigGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PriceConfigGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PriceConfigGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PriceConfigGroupByOutputType[P]>
      }
    >
  >



export type PriceConfigWhereInput = {
  AND?: Prisma.PriceConfigWhereInput | Prisma.PriceConfigWhereInput[]
  OR?: Prisma.PriceConfigWhereInput[]
  NOT?: Prisma.PriceConfigWhereInput | Prisma.PriceConfigWhereInput[]
  id?: Prisma.IntFilter<"PriceConfig"> | number
  pricePerSheet?: Prisma.FloatFilter<"PriceConfig"> | number
  inkCost?: Prisma.FloatFilter<"PriceConfig"> | number
  laminationCost?: Prisma.FloatFilter<"PriceConfig"> | number
  deckboxPrice?: Prisma.FloatFilter<"PriceConfig"> | number
  sleevesPrice?: Prisma.FloatFilter<"PriceConfig"> | number
  updatedAt?: Prisma.DateTimeFilter<"PriceConfig"> | Date | string
}

export type PriceConfigOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  pricePerSheet?: Prisma.SortOrder
  inkCost?: Prisma.SortOrder
  laminationCost?: Prisma.SortOrder
  deckboxPrice?: Prisma.SortOrder
  sleevesPrice?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PriceConfigWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.PriceConfigWhereInput | Prisma.PriceConfigWhereInput[]
  OR?: Prisma.PriceConfigWhereInput[]
  NOT?: Prisma.PriceConfigWhereInput | Prisma.PriceConfigWhereInput[]
  pricePerSheet?: Prisma.FloatFilter<"PriceConfig"> | number
  inkCost?: Prisma.FloatFilter<"PriceConfig"> | number
  laminationCost?: Prisma.FloatFilter<"PriceConfig"> | number
  deckboxPrice?: Prisma.FloatFilter<"PriceConfig"> | number
  sleevesPrice?: Prisma.FloatFilter<"PriceConfig"> | number
  updatedAt?: Prisma.DateTimeFilter<"PriceConfig"> | Date | string
}, "id">

export type PriceConfigOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  pricePerSheet?: Prisma.SortOrder
  inkCost?: Prisma.SortOrder
  laminationCost?: Prisma.SortOrder
  deckboxPrice?: Prisma.SortOrder
  sleevesPrice?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PriceConfigCountOrderByAggregateInput
  _avg?: Prisma.PriceConfigAvgOrderByAggregateInput
  _max?: Prisma.PriceConfigMaxOrderByAggregateInput
  _min?: Prisma.PriceConfigMinOrderByAggregateInput
  _sum?: Prisma.PriceConfigSumOrderByAggregateInput
}

export type PriceConfigScalarWhereWithAggregatesInput = {
  AND?: Prisma.PriceConfigScalarWhereWithAggregatesInput | Prisma.PriceConfigScalarWhereWithAggregatesInput[]
  OR?: Prisma.PriceConfigScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PriceConfigScalarWhereWithAggregatesInput | Prisma.PriceConfigScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"PriceConfig"> | number
  pricePerSheet?: Prisma.FloatWithAggregatesFilter<"PriceConfig"> | number
  inkCost?: Prisma.FloatWithAggregatesFilter<"PriceConfig"> | number
  laminationCost?: Prisma.FloatWithAggregatesFilter<"PriceConfig"> | number
  deckboxPrice?: Prisma.FloatWithAggregatesFilter<"PriceConfig"> | number
  sleevesPrice?: Prisma.FloatWithAggregatesFilter<"PriceConfig"> | number
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PriceConfig"> | Date | string
}

export type PriceConfigCreateInput = {
  id: number
  pricePerSheet: number
  inkCost: number
  laminationCost: number
  deckboxPrice: number
  sleevesPrice: number
  updatedAt?: Date | string
}

export type PriceConfigUncheckedCreateInput = {
  id: number
  pricePerSheet: number
  inkCost: number
  laminationCost: number
  deckboxPrice: number
  sleevesPrice: number
  updatedAt?: Date | string
}

export type PriceConfigUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  pricePerSheet?: Prisma.FloatFieldUpdateOperationsInput | number
  inkCost?: Prisma.FloatFieldUpdateOperationsInput | number
  laminationCost?: Prisma.FloatFieldUpdateOperationsInput | number
  deckboxPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  sleevesPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PriceConfigUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  pricePerSheet?: Prisma.FloatFieldUpdateOperationsInput | number
  inkCost?: Prisma.FloatFieldUpdateOperationsInput | number
  laminationCost?: Prisma.FloatFieldUpdateOperationsInput | number
  deckboxPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  sleevesPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PriceConfigCreateManyInput = {
  id: number
  pricePerSheet: number
  inkCost: number
  laminationCost: number
  deckboxPrice: number
  sleevesPrice: number
  updatedAt?: Date | string
}

export type PriceConfigUpdateManyMutationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  pricePerSheet?: Prisma.FloatFieldUpdateOperationsInput | number
  inkCost?: Prisma.FloatFieldUpdateOperationsInput | number
  laminationCost?: Prisma.FloatFieldUpdateOperationsInput | number
  deckboxPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  sleevesPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PriceConfigUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  pricePerSheet?: Prisma.FloatFieldUpdateOperationsInput | number
  inkCost?: Prisma.FloatFieldUpdateOperationsInput | number
  laminationCost?: Prisma.FloatFieldUpdateOperationsInput | number
  deckboxPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  sleevesPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PriceConfigCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pricePerSheet?: Prisma.SortOrder
  inkCost?: Prisma.SortOrder
  laminationCost?: Prisma.SortOrder
  deckboxPrice?: Prisma.SortOrder
  sleevesPrice?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PriceConfigAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pricePerSheet?: Prisma.SortOrder
  inkCost?: Prisma.SortOrder
  laminationCost?: Prisma.SortOrder
  deckboxPrice?: Prisma.SortOrder
  sleevesPrice?: Prisma.SortOrder
}

export type PriceConfigMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pricePerSheet?: Prisma.SortOrder
  inkCost?: Prisma.SortOrder
  laminationCost?: Prisma.SortOrder
  deckboxPrice?: Prisma.SortOrder
  sleevesPrice?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PriceConfigMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pricePerSheet?: Prisma.SortOrder
  inkCost?: Prisma.SortOrder
  laminationCost?: Prisma.SortOrder
  deckboxPrice?: Prisma.SortOrder
  sleevesPrice?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PriceConfigSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pricePerSheet?: Prisma.SortOrder
  inkCost?: Prisma.SortOrder
  laminationCost?: Prisma.SortOrder
  deckboxPrice?: Prisma.SortOrder
  sleevesPrice?: Prisma.SortOrder
}



export type PriceConfigSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pricePerSheet?: boolean
  inkCost?: boolean
  laminationCost?: boolean
  deckboxPrice?: boolean
  sleevesPrice?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["priceConfig"]>

export type PriceConfigSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pricePerSheet?: boolean
  inkCost?: boolean
  laminationCost?: boolean
  deckboxPrice?: boolean
  sleevesPrice?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["priceConfig"]>

export type PriceConfigSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pricePerSheet?: boolean
  inkCost?: boolean
  laminationCost?: boolean
  deckboxPrice?: boolean
  sleevesPrice?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["priceConfig"]>

export type PriceConfigSelectScalar = {
  id?: boolean
  pricePerSheet?: boolean
  inkCost?: boolean
  laminationCost?: boolean
  deckboxPrice?: boolean
  sleevesPrice?: boolean
  updatedAt?: boolean
}

export type PriceConfigOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "pricePerSheet" | "inkCost" | "laminationCost" | "deckboxPrice" | "sleevesPrice" | "updatedAt", ExtArgs["result"]["priceConfig"]>

export type $PriceConfigPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PriceConfig"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    pricePerSheet: number
    inkCost: number
    laminationCost: number
    deckboxPrice: number
    sleevesPrice: number
    updatedAt: Date
  }, ExtArgs["result"]["priceConfig"]>
  composites: {}
}

export type PriceConfigGetPayload<S extends boolean | null | undefined | PriceConfigDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PriceConfigPayload, S>

export type PriceConfigCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PriceConfigFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PriceConfigCountAggregateInputType | true
  }

export interface PriceConfigDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PriceConfig'], meta: { name: 'PriceConfig' } }
  /**
   * Find zero or one PriceConfig that matches the filter.
   * @param {PriceConfigFindUniqueArgs} args - Arguments to find a PriceConfig
   * @example
   * // Get one PriceConfig
   * const priceConfig = await prisma.priceConfig.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PriceConfigFindUniqueArgs>(args: Prisma.SelectSubset<T, PriceConfigFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PriceConfigClient<runtime.Types.Result.GetResult<Prisma.$PriceConfigPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PriceConfig that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PriceConfigFindUniqueOrThrowArgs} args - Arguments to find a PriceConfig
   * @example
   * // Get one PriceConfig
   * const priceConfig = await prisma.priceConfig.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PriceConfigFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PriceConfigFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PriceConfigClient<runtime.Types.Result.GetResult<Prisma.$PriceConfigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PriceConfig that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceConfigFindFirstArgs} args - Arguments to find a PriceConfig
   * @example
   * // Get one PriceConfig
   * const priceConfig = await prisma.priceConfig.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PriceConfigFindFirstArgs>(args?: Prisma.SelectSubset<T, PriceConfigFindFirstArgs<ExtArgs>>): Prisma.Prisma__PriceConfigClient<runtime.Types.Result.GetResult<Prisma.$PriceConfigPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PriceConfig that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceConfigFindFirstOrThrowArgs} args - Arguments to find a PriceConfig
   * @example
   * // Get one PriceConfig
   * const priceConfig = await prisma.priceConfig.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PriceConfigFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PriceConfigFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PriceConfigClient<runtime.Types.Result.GetResult<Prisma.$PriceConfigPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PriceConfigs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceConfigFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PriceConfigs
   * const priceConfigs = await prisma.priceConfig.findMany()
   * 
   * // Get first 10 PriceConfigs
   * const priceConfigs = await prisma.priceConfig.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const priceConfigWithIdOnly = await prisma.priceConfig.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PriceConfigFindManyArgs>(args?: Prisma.SelectSubset<T, PriceConfigFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PriceConfigPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PriceConfig.
   * @param {PriceConfigCreateArgs} args - Arguments to create a PriceConfig.
   * @example
   * // Create one PriceConfig
   * const PriceConfig = await prisma.priceConfig.create({
   *   data: {
   *     // ... data to create a PriceConfig
   *   }
   * })
   * 
   */
  create<T extends PriceConfigCreateArgs>(args: Prisma.SelectSubset<T, PriceConfigCreateArgs<ExtArgs>>): Prisma.Prisma__PriceConfigClient<runtime.Types.Result.GetResult<Prisma.$PriceConfigPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PriceConfigs.
   * @param {PriceConfigCreateManyArgs} args - Arguments to create many PriceConfigs.
   * @example
   * // Create many PriceConfigs
   * const priceConfig = await prisma.priceConfig.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PriceConfigCreateManyArgs>(args?: Prisma.SelectSubset<T, PriceConfigCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PriceConfigs and returns the data saved in the database.
   * @param {PriceConfigCreateManyAndReturnArgs} args - Arguments to create many PriceConfigs.
   * @example
   * // Create many PriceConfigs
   * const priceConfig = await prisma.priceConfig.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PriceConfigs and only return the `id`
   * const priceConfigWithIdOnly = await prisma.priceConfig.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PriceConfigCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PriceConfigCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PriceConfigPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PriceConfig.
   * @param {PriceConfigDeleteArgs} args - Arguments to delete one PriceConfig.
   * @example
   * // Delete one PriceConfig
   * const PriceConfig = await prisma.priceConfig.delete({
   *   where: {
   *     // ... filter to delete one PriceConfig
   *   }
   * })
   * 
   */
  delete<T extends PriceConfigDeleteArgs>(args: Prisma.SelectSubset<T, PriceConfigDeleteArgs<ExtArgs>>): Prisma.Prisma__PriceConfigClient<runtime.Types.Result.GetResult<Prisma.$PriceConfigPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PriceConfig.
   * @param {PriceConfigUpdateArgs} args - Arguments to update one PriceConfig.
   * @example
   * // Update one PriceConfig
   * const priceConfig = await prisma.priceConfig.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PriceConfigUpdateArgs>(args: Prisma.SelectSubset<T, PriceConfigUpdateArgs<ExtArgs>>): Prisma.Prisma__PriceConfigClient<runtime.Types.Result.GetResult<Prisma.$PriceConfigPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PriceConfigs.
   * @param {PriceConfigDeleteManyArgs} args - Arguments to filter PriceConfigs to delete.
   * @example
   * // Delete a few PriceConfigs
   * const { count } = await prisma.priceConfig.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PriceConfigDeleteManyArgs>(args?: Prisma.SelectSubset<T, PriceConfigDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PriceConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceConfigUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PriceConfigs
   * const priceConfig = await prisma.priceConfig.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PriceConfigUpdateManyArgs>(args: Prisma.SelectSubset<T, PriceConfigUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PriceConfigs and returns the data updated in the database.
   * @param {PriceConfigUpdateManyAndReturnArgs} args - Arguments to update many PriceConfigs.
   * @example
   * // Update many PriceConfigs
   * const priceConfig = await prisma.priceConfig.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PriceConfigs and only return the `id`
   * const priceConfigWithIdOnly = await prisma.priceConfig.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PriceConfigUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PriceConfigUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PriceConfigPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PriceConfig.
   * @param {PriceConfigUpsertArgs} args - Arguments to update or create a PriceConfig.
   * @example
   * // Update or create a PriceConfig
   * const priceConfig = await prisma.priceConfig.upsert({
   *   create: {
   *     // ... data to create a PriceConfig
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PriceConfig we want to update
   *   }
   * })
   */
  upsert<T extends PriceConfigUpsertArgs>(args: Prisma.SelectSubset<T, PriceConfigUpsertArgs<ExtArgs>>): Prisma.Prisma__PriceConfigClient<runtime.Types.Result.GetResult<Prisma.$PriceConfigPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PriceConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceConfigCountArgs} args - Arguments to filter PriceConfigs to count.
   * @example
   * // Count the number of PriceConfigs
   * const count = await prisma.priceConfig.count({
   *   where: {
   *     // ... the filter for the PriceConfigs we want to count
   *   }
   * })
  **/
  count<T extends PriceConfigCountArgs>(
    args?: Prisma.Subset<T, PriceConfigCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PriceConfigCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PriceConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceConfigAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PriceConfigAggregateArgs>(args: Prisma.Subset<T, PriceConfigAggregateArgs>): Prisma.PrismaPromise<GetPriceConfigAggregateType<T>>

  /**
   * Group by PriceConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceConfigGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PriceConfigGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PriceConfigGroupByArgs['orderBy'] }
      : { orderBy?: PriceConfigGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PriceConfigGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPriceConfigGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PriceConfig model
 */
readonly fields: PriceConfigFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PriceConfig.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PriceConfigClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PriceConfig model
 */
export interface PriceConfigFieldRefs {
  readonly id: Prisma.FieldRef<"PriceConfig", 'Int'>
  readonly pricePerSheet: Prisma.FieldRef<"PriceConfig", 'Float'>
  readonly inkCost: Prisma.FieldRef<"PriceConfig", 'Float'>
  readonly laminationCost: Prisma.FieldRef<"PriceConfig", 'Float'>
  readonly deckboxPrice: Prisma.FieldRef<"PriceConfig", 'Float'>
  readonly sleevesPrice: Prisma.FieldRef<"PriceConfig", 'Float'>
  readonly updatedAt: Prisma.FieldRef<"PriceConfig", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PriceConfig findUnique
 */
export type PriceConfigFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceConfig
   */
  select?: Prisma.PriceConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceConfig
   */
  omit?: Prisma.PriceConfigOmit<ExtArgs> | null
  /**
   * Filter, which PriceConfig to fetch.
   */
  where: Prisma.PriceConfigWhereUniqueInput
}

/**
 * PriceConfig findUniqueOrThrow
 */
export type PriceConfigFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceConfig
   */
  select?: Prisma.PriceConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceConfig
   */
  omit?: Prisma.PriceConfigOmit<ExtArgs> | null
  /**
   * Filter, which PriceConfig to fetch.
   */
  where: Prisma.PriceConfigWhereUniqueInput
}

/**
 * PriceConfig findFirst
 */
export type PriceConfigFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceConfig
   */
  select?: Prisma.PriceConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceConfig
   */
  omit?: Prisma.PriceConfigOmit<ExtArgs> | null
  /**
   * Filter, which PriceConfig to fetch.
   */
  where?: Prisma.PriceConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PriceConfigs to fetch.
   */
  orderBy?: Prisma.PriceConfigOrderByWithRelationInput | Prisma.PriceConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PriceConfigs.
   */
  cursor?: Prisma.PriceConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PriceConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PriceConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PriceConfigs.
   */
  distinct?: Prisma.PriceConfigScalarFieldEnum | Prisma.PriceConfigScalarFieldEnum[]
}

/**
 * PriceConfig findFirstOrThrow
 */
export type PriceConfigFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceConfig
   */
  select?: Prisma.PriceConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceConfig
   */
  omit?: Prisma.PriceConfigOmit<ExtArgs> | null
  /**
   * Filter, which PriceConfig to fetch.
   */
  where?: Prisma.PriceConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PriceConfigs to fetch.
   */
  orderBy?: Prisma.PriceConfigOrderByWithRelationInput | Prisma.PriceConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PriceConfigs.
   */
  cursor?: Prisma.PriceConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PriceConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PriceConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PriceConfigs.
   */
  distinct?: Prisma.PriceConfigScalarFieldEnum | Prisma.PriceConfigScalarFieldEnum[]
}

/**
 * PriceConfig findMany
 */
export type PriceConfigFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceConfig
   */
  select?: Prisma.PriceConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceConfig
   */
  omit?: Prisma.PriceConfigOmit<ExtArgs> | null
  /**
   * Filter, which PriceConfigs to fetch.
   */
  where?: Prisma.PriceConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PriceConfigs to fetch.
   */
  orderBy?: Prisma.PriceConfigOrderByWithRelationInput | Prisma.PriceConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PriceConfigs.
   */
  cursor?: Prisma.PriceConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PriceConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PriceConfigs.
   */
  skip?: number
  distinct?: Prisma.PriceConfigScalarFieldEnum | Prisma.PriceConfigScalarFieldEnum[]
}

/**
 * PriceConfig create
 */
export type PriceConfigCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceConfig
   */
  select?: Prisma.PriceConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceConfig
   */
  omit?: Prisma.PriceConfigOmit<ExtArgs> | null
  /**
   * The data needed to create a PriceConfig.
   */
  data: Prisma.XOR<Prisma.PriceConfigCreateInput, Prisma.PriceConfigUncheckedCreateInput>
}

/**
 * PriceConfig createMany
 */
export type PriceConfigCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PriceConfigs.
   */
  data: Prisma.PriceConfigCreateManyInput | Prisma.PriceConfigCreateManyInput[]
}

/**
 * PriceConfig createManyAndReturn
 */
export type PriceConfigCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceConfig
   */
  select?: Prisma.PriceConfigSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PriceConfig
   */
  omit?: Prisma.PriceConfigOmit<ExtArgs> | null
  /**
   * The data used to create many PriceConfigs.
   */
  data: Prisma.PriceConfigCreateManyInput | Prisma.PriceConfigCreateManyInput[]
}

/**
 * PriceConfig update
 */
export type PriceConfigUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceConfig
   */
  select?: Prisma.PriceConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceConfig
   */
  omit?: Prisma.PriceConfigOmit<ExtArgs> | null
  /**
   * The data needed to update a PriceConfig.
   */
  data: Prisma.XOR<Prisma.PriceConfigUpdateInput, Prisma.PriceConfigUncheckedUpdateInput>
  /**
   * Choose, which PriceConfig to update.
   */
  where: Prisma.PriceConfigWhereUniqueInput
}

/**
 * PriceConfig updateMany
 */
export type PriceConfigUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PriceConfigs.
   */
  data: Prisma.XOR<Prisma.PriceConfigUpdateManyMutationInput, Prisma.PriceConfigUncheckedUpdateManyInput>
  /**
   * Filter which PriceConfigs to update
   */
  where?: Prisma.PriceConfigWhereInput
  /**
   * Limit how many PriceConfigs to update.
   */
  limit?: number
}

/**
 * PriceConfig updateManyAndReturn
 */
export type PriceConfigUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceConfig
   */
  select?: Prisma.PriceConfigSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PriceConfig
   */
  omit?: Prisma.PriceConfigOmit<ExtArgs> | null
  /**
   * The data used to update PriceConfigs.
   */
  data: Prisma.XOR<Prisma.PriceConfigUpdateManyMutationInput, Prisma.PriceConfigUncheckedUpdateManyInput>
  /**
   * Filter which PriceConfigs to update
   */
  where?: Prisma.PriceConfigWhereInput
  /**
   * Limit how many PriceConfigs to update.
   */
  limit?: number
}

/**
 * PriceConfig upsert
 */
export type PriceConfigUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceConfig
   */
  select?: Prisma.PriceConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceConfig
   */
  omit?: Prisma.PriceConfigOmit<ExtArgs> | null
  /**
   * The filter to search for the PriceConfig to update in case it exists.
   */
  where: Prisma.PriceConfigWhereUniqueInput
  /**
   * In case the PriceConfig found by the `where` argument doesn't exist, create a new PriceConfig with this data.
   */
  create: Prisma.XOR<Prisma.PriceConfigCreateInput, Prisma.PriceConfigUncheckedCreateInput>
  /**
   * In case the PriceConfig was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PriceConfigUpdateInput, Prisma.PriceConfigUncheckedUpdateInput>
}

/**
 * PriceConfig delete
 */
export type PriceConfigDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceConfig
   */
  select?: Prisma.PriceConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceConfig
   */
  omit?: Prisma.PriceConfigOmit<ExtArgs> | null
  /**
   * Filter which PriceConfig to delete.
   */
  where: Prisma.PriceConfigWhereUniqueInput
}

/**
 * PriceConfig deleteMany
 */
export type PriceConfigDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PriceConfigs to delete
   */
  where?: Prisma.PriceConfigWhereInput
  /**
   * Limit how many PriceConfigs to delete.
   */
  limit?: number
}

/**
 * PriceConfig without action
 */
export type PriceConfigDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceConfig
   */
  select?: Prisma.PriceConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceConfig
   */
  omit?: Prisma.PriceConfigOmit<ExtArgs> | null
}
