
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `TicketOrder` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TicketOrder
 * 
 */
export type TicketOrderModel = runtime.Types.Result.DefaultSelection<Prisma.$TicketOrderPayload>

export type AggregateTicketOrder = {
  _count: TicketOrderCountAggregateOutputType | null
  _avg: TicketOrderAvgAggregateOutputType | null
  _sum: TicketOrderSumAggregateOutputType | null
  _min: TicketOrderMinAggregateOutputType | null
  _max: TicketOrderMaxAggregateOutputType | null
}

export type TicketOrderAvgAggregateOutputType = {
  cardCount: number | null
  sheetCount: number | null
  materialCostCents: number | null
  profitMarginPercent: number | null
  finalPriceCents: number | null
}

export type TicketOrderSumAggregateOutputType = {
  cardCount: number | null
  sheetCount: number | null
  materialCostCents: number | null
  profitMarginPercent: number | null
  finalPriceCents: number | null
}

export type TicketOrderMinAggregateOutputType = {
  oid: string | null
  guildId: string | null
  channelId: string | null
  userId: string | null
  responsibleAdminId: string | null
  status: $Enums.TicketOrderStatus | null
  cardType: $Enums.TicketOrderCardType | null
  cardCount: number | null
  deckLink: string | null
  sheetCount: number | null
  materialCostCents: number | null
  profitMarginPercent: number | null
  finalPriceCents: number | null
  paymentId: string | null
  paymentMessageId: string | null
  paymentStatus: string | null
  paymentQrCodeBase64: string | null
  paymentCopyPaste: string | null
  paymentExpiresAt: Date | null
  paidAt: Date | null
  cancelledAt: Date | null
  confirmedAt: Date | null
  concludedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TicketOrderMaxAggregateOutputType = {
  oid: string | null
  guildId: string | null
  channelId: string | null
  userId: string | null
  responsibleAdminId: string | null
  status: $Enums.TicketOrderStatus | null
  cardType: $Enums.TicketOrderCardType | null
  cardCount: number | null
  deckLink: string | null
  sheetCount: number | null
  materialCostCents: number | null
  profitMarginPercent: number | null
  finalPriceCents: number | null
  paymentId: string | null
  paymentMessageId: string | null
  paymentStatus: string | null
  paymentQrCodeBase64: string | null
  paymentCopyPaste: string | null
  paymentExpiresAt: Date | null
  paidAt: Date | null
  cancelledAt: Date | null
  confirmedAt: Date | null
  concludedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TicketOrderCountAggregateOutputType = {
  oid: number
  guildId: number
  channelId: number
  userId: number
  responsibleAdminId: number
  status: number
  cardType: number
  cardCount: number
  deckLink: number
  sheetCount: number
  materialCostCents: number
  profitMarginPercent: number
  finalPriceCents: number
  paymentId: number
  paymentMessageId: number
  paymentStatus: number
  paymentQrCodeBase64: number
  paymentCopyPaste: number
  paymentExpiresAt: number
  paidAt: number
  cancelledAt: number
  confirmedAt: number
  concludedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TicketOrderAvgAggregateInputType = {
  cardCount?: true
  sheetCount?: true
  materialCostCents?: true
  profitMarginPercent?: true
  finalPriceCents?: true
}

export type TicketOrderSumAggregateInputType = {
  cardCount?: true
  sheetCount?: true
  materialCostCents?: true
  profitMarginPercent?: true
  finalPriceCents?: true
}

export type TicketOrderMinAggregateInputType = {
  oid?: true
  guildId?: true
  channelId?: true
  userId?: true
  responsibleAdminId?: true
  status?: true
  cardType?: true
  cardCount?: true
  deckLink?: true
  sheetCount?: true
  materialCostCents?: true
  profitMarginPercent?: true
  finalPriceCents?: true
  paymentId?: true
  paymentMessageId?: true
  paymentStatus?: true
  paymentQrCodeBase64?: true
  paymentCopyPaste?: true
  paymentExpiresAt?: true
  paidAt?: true
  cancelledAt?: true
  confirmedAt?: true
  concludedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type TicketOrderMaxAggregateInputType = {
  oid?: true
  guildId?: true
  channelId?: true
  userId?: true
  responsibleAdminId?: true
  status?: true
  cardType?: true
  cardCount?: true
  deckLink?: true
  sheetCount?: true
  materialCostCents?: true
  profitMarginPercent?: true
  finalPriceCents?: true
  paymentId?: true
  paymentMessageId?: true
  paymentStatus?: true
  paymentQrCodeBase64?: true
  paymentCopyPaste?: true
  paymentExpiresAt?: true
  paidAt?: true
  cancelledAt?: true
  confirmedAt?: true
  concludedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type TicketOrderCountAggregateInputType = {
  oid?: true
  guildId?: true
  channelId?: true
  userId?: true
  responsibleAdminId?: true
  status?: true
  cardType?: true
  cardCount?: true
  deckLink?: true
  sheetCount?: true
  materialCostCents?: true
  profitMarginPercent?: true
  finalPriceCents?: true
  paymentId?: true
  paymentMessageId?: true
  paymentStatus?: true
  paymentQrCodeBase64?: true
  paymentCopyPaste?: true
  paymentExpiresAt?: true
  paidAt?: true
  cancelledAt?: true
  confirmedAt?: true
  concludedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TicketOrderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TicketOrder to aggregate.
   */
  where?: Prisma.TicketOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketOrders to fetch.
   */
  orderBy?: Prisma.TicketOrderOrderByWithRelationInput | Prisma.TicketOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TicketOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TicketOrders
  **/
  _count?: true | TicketOrderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TicketOrderAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TicketOrderSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TicketOrderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TicketOrderMaxAggregateInputType
}

export type GetTicketOrderAggregateType<T extends TicketOrderAggregateArgs> = {
      [P in keyof T & keyof AggregateTicketOrder]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTicketOrder[P]>
    : Prisma.GetScalarType<T[P], AggregateTicketOrder[P]>
}




export type TicketOrderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TicketOrderWhereInput
  orderBy?: Prisma.TicketOrderOrderByWithAggregationInput | Prisma.TicketOrderOrderByWithAggregationInput[]
  by: Prisma.TicketOrderScalarFieldEnum[] | Prisma.TicketOrderScalarFieldEnum
  having?: Prisma.TicketOrderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TicketOrderCountAggregateInputType | true
  _avg?: TicketOrderAvgAggregateInputType
  _sum?: TicketOrderSumAggregateInputType
  _min?: TicketOrderMinAggregateInputType
  _max?: TicketOrderMaxAggregateInputType
}

export type TicketOrderGroupByOutputType = {
  oid: string
  guildId: string
  channelId: string
  userId: string
  responsibleAdminId: string | null
  status: $Enums.TicketOrderStatus
  cardType: $Enums.TicketOrderCardType | null
  cardCount: number | null
  deckLink: string | null
  sheetCount: number | null
  materialCostCents: number | null
  profitMarginPercent: number | null
  finalPriceCents: number | null
  paymentId: string | null
  paymentMessageId: string | null
  paymentStatus: string | null
  paymentQrCodeBase64: string | null
  paymentCopyPaste: string | null
  paymentExpiresAt: Date | null
  paidAt: Date | null
  cancelledAt: Date | null
  confirmedAt: Date | null
  concludedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: TicketOrderCountAggregateOutputType | null
  _avg: TicketOrderAvgAggregateOutputType | null
  _sum: TicketOrderSumAggregateOutputType | null
  _min: TicketOrderMinAggregateOutputType | null
  _max: TicketOrderMaxAggregateOutputType | null
}

type GetTicketOrderGroupByPayload<T extends TicketOrderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TicketOrderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TicketOrderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TicketOrderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TicketOrderGroupByOutputType[P]>
      }
    >
  >



export type TicketOrderWhereInput = {
  AND?: Prisma.TicketOrderWhereInput | Prisma.TicketOrderWhereInput[]
  OR?: Prisma.TicketOrderWhereInput[]
  NOT?: Prisma.TicketOrderWhereInput | Prisma.TicketOrderWhereInput[]
  oid?: Prisma.StringFilter<"TicketOrder"> | string
  guildId?: Prisma.StringFilter<"TicketOrder"> | string
  channelId?: Prisma.StringFilter<"TicketOrder"> | string
  userId?: Prisma.StringFilter<"TicketOrder"> | string
  responsibleAdminId?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  status?: Prisma.EnumTicketOrderStatusFilter<"TicketOrder"> | $Enums.TicketOrderStatus
  cardType?: Prisma.EnumTicketOrderCardTypeNullableFilter<"TicketOrder"> | $Enums.TicketOrderCardType | null
  cardCount?: Prisma.IntNullableFilter<"TicketOrder"> | number | null
  deckLink?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  sheetCount?: Prisma.IntNullableFilter<"TicketOrder"> | number | null
  materialCostCents?: Prisma.IntNullableFilter<"TicketOrder"> | number | null
  profitMarginPercent?: Prisma.IntNullableFilter<"TicketOrder"> | number | null
  finalPriceCents?: Prisma.IntNullableFilter<"TicketOrder"> | number | null
  paymentId?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  paymentMessageId?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  paymentStatus?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  paymentQrCodeBase64?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  paymentCopyPaste?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  paymentExpiresAt?: Prisma.DateTimeNullableFilter<"TicketOrder"> | Date | string | null
  paidAt?: Prisma.DateTimeNullableFilter<"TicketOrder"> | Date | string | null
  cancelledAt?: Prisma.DateTimeNullableFilter<"TicketOrder"> | Date | string | null
  confirmedAt?: Prisma.DateTimeNullableFilter<"TicketOrder"> | Date | string | null
  concludedAt?: Prisma.DateTimeNullableFilter<"TicketOrder"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"TicketOrder"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TicketOrder"> | Date | string
  guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>
}

export type TicketOrderOrderByWithRelationInput = {
  oid?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  responsibleAdminId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  cardType?: Prisma.SortOrder
  cardCount?: Prisma.SortOrder
  deckLink?: Prisma.SortOrder
  sheetCount?: Prisma.SortOrder
  materialCostCents?: Prisma.SortOrder
  profitMarginPercent?: Prisma.SortOrder
  finalPriceCents?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  paymentMessageId?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  paymentQrCodeBase64?: Prisma.SortOrder
  paymentCopyPaste?: Prisma.SortOrder
  paymentExpiresAt?: Prisma.SortOrder
  paidAt?: Prisma.SortOrder
  cancelledAt?: Prisma.SortOrder
  confirmedAt?: Prisma.SortOrder
  concludedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  guild?: Prisma.GuildOrderByWithRelationInput
}

export type TicketOrderWhereUniqueInput = Prisma.AtLeast<{
  oid?: string
  channelId?: string
  AND?: Prisma.TicketOrderWhereInput | Prisma.TicketOrderWhereInput[]
  OR?: Prisma.TicketOrderWhereInput[]
  NOT?: Prisma.TicketOrderWhereInput | Prisma.TicketOrderWhereInput[]
  guildId?: Prisma.StringFilter<"TicketOrder"> | string
  userId?: Prisma.StringFilter<"TicketOrder"> | string
  responsibleAdminId?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  status?: Prisma.EnumTicketOrderStatusFilter<"TicketOrder"> | $Enums.TicketOrderStatus
  cardType?: Prisma.EnumTicketOrderCardTypeNullableFilter<"TicketOrder"> | $Enums.TicketOrderCardType | null
  cardCount?: Prisma.IntNullableFilter<"TicketOrder"> | number | null
  deckLink?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  sheetCount?: Prisma.IntNullableFilter<"TicketOrder"> | number | null
  materialCostCents?: Prisma.IntNullableFilter<"TicketOrder"> | number | null
  profitMarginPercent?: Prisma.IntNullableFilter<"TicketOrder"> | number | null
  finalPriceCents?: Prisma.IntNullableFilter<"TicketOrder"> | number | null
  paymentId?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  paymentMessageId?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  paymentStatus?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  paymentQrCodeBase64?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  paymentCopyPaste?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  paymentExpiresAt?: Prisma.DateTimeNullableFilter<"TicketOrder"> | Date | string | null
  paidAt?: Prisma.DateTimeNullableFilter<"TicketOrder"> | Date | string | null
  cancelledAt?: Prisma.DateTimeNullableFilter<"TicketOrder"> | Date | string | null
  confirmedAt?: Prisma.DateTimeNullableFilter<"TicketOrder"> | Date | string | null
  concludedAt?: Prisma.DateTimeNullableFilter<"TicketOrder"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"TicketOrder"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TicketOrder"> | Date | string
  guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>
}, "oid" | "channelId">

export type TicketOrderOrderByWithAggregationInput = {
  oid?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  responsibleAdminId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  cardType?: Prisma.SortOrder
  cardCount?: Prisma.SortOrder
  deckLink?: Prisma.SortOrder
  sheetCount?: Prisma.SortOrder
  materialCostCents?: Prisma.SortOrder
  profitMarginPercent?: Prisma.SortOrder
  finalPriceCents?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  paymentMessageId?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  paymentQrCodeBase64?: Prisma.SortOrder
  paymentCopyPaste?: Prisma.SortOrder
  paymentExpiresAt?: Prisma.SortOrder
  paidAt?: Prisma.SortOrder
  cancelledAt?: Prisma.SortOrder
  confirmedAt?: Prisma.SortOrder
  concludedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TicketOrderCountOrderByAggregateInput
  _avg?: Prisma.TicketOrderAvgOrderByAggregateInput
  _max?: Prisma.TicketOrderMaxOrderByAggregateInput
  _min?: Prisma.TicketOrderMinOrderByAggregateInput
  _sum?: Prisma.TicketOrderSumOrderByAggregateInput
}

export type TicketOrderScalarWhereWithAggregatesInput = {
  AND?: Prisma.TicketOrderScalarWhereWithAggregatesInput | Prisma.TicketOrderScalarWhereWithAggregatesInput[]
  OR?: Prisma.TicketOrderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TicketOrderScalarWhereWithAggregatesInput | Prisma.TicketOrderScalarWhereWithAggregatesInput[]
  oid?: Prisma.StringWithAggregatesFilter<"TicketOrder"> | string
  guildId?: Prisma.StringWithAggregatesFilter<"TicketOrder"> | string
  channelId?: Prisma.StringWithAggregatesFilter<"TicketOrder"> | string
  userId?: Prisma.StringWithAggregatesFilter<"TicketOrder"> | string
  responsibleAdminId?: Prisma.StringNullableWithAggregatesFilter<"TicketOrder"> | string | null
  status?: Prisma.EnumTicketOrderStatusWithAggregatesFilter<"TicketOrder"> | $Enums.TicketOrderStatus
  cardType?: Prisma.EnumTicketOrderCardTypeNullableWithAggregatesFilter<"TicketOrder"> | $Enums.TicketOrderCardType | null
  cardCount?: Prisma.IntNullableWithAggregatesFilter<"TicketOrder"> | number | null
  deckLink?: Prisma.StringNullableWithAggregatesFilter<"TicketOrder"> | string | null
  sheetCount?: Prisma.IntNullableWithAggregatesFilter<"TicketOrder"> | number | null
  materialCostCents?: Prisma.IntNullableWithAggregatesFilter<"TicketOrder"> | number | null
  profitMarginPercent?: Prisma.IntNullableWithAggregatesFilter<"TicketOrder"> | number | null
  finalPriceCents?: Prisma.IntNullableWithAggregatesFilter<"TicketOrder"> | number | null
  paymentId?: Prisma.StringNullableWithAggregatesFilter<"TicketOrder"> | string | null
  paymentMessageId?: Prisma.StringNullableWithAggregatesFilter<"TicketOrder"> | string | null
  paymentStatus?: Prisma.StringNullableWithAggregatesFilter<"TicketOrder"> | string | null
  paymentQrCodeBase64?: Prisma.StringNullableWithAggregatesFilter<"TicketOrder"> | string | null
  paymentCopyPaste?: Prisma.StringNullableWithAggregatesFilter<"TicketOrder"> | string | null
  paymentExpiresAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TicketOrder"> | Date | string | null
  paidAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TicketOrder"> | Date | string | null
  cancelledAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TicketOrder"> | Date | string | null
  confirmedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TicketOrder"> | Date | string | null
  concludedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TicketOrder"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TicketOrder"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TicketOrder"> | Date | string
}

export type TicketOrderCreateInput = {
  oid?: string
  channelId: string
  userId: string
  responsibleAdminId?: string | null
  status?: $Enums.TicketOrderStatus
  cardType?: $Enums.TicketOrderCardType | null
  cardCount?: number | null
  deckLink?: string | null
  sheetCount?: number | null
  materialCostCents?: number | null
  profitMarginPercent?: number | null
  finalPriceCents?: number | null
  paymentId?: string | null
  paymentMessageId?: string | null
  paymentStatus?: string | null
  paymentQrCodeBase64?: string | null
  paymentCopyPaste?: string | null
  paymentExpiresAt?: Date | string | null
  paidAt?: Date | string | null
  cancelledAt?: Date | string | null
  confirmedAt?: Date | string | null
  concludedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  guild: Prisma.GuildCreateNestedOneWithoutTicketOrdersInput
}

export type TicketOrderUncheckedCreateInput = {
  oid?: string
  guildId: string
  channelId: string
  userId: string
  responsibleAdminId?: string | null
  status?: $Enums.TicketOrderStatus
  cardType?: $Enums.TicketOrderCardType | null
  cardCount?: number | null
  deckLink?: string | null
  sheetCount?: number | null
  materialCostCents?: number | null
  profitMarginPercent?: number | null
  finalPriceCents?: number | null
  paymentId?: string | null
  paymentMessageId?: string | null
  paymentStatus?: string | null
  paymentQrCodeBase64?: string | null
  paymentCopyPaste?: string | null
  paymentExpiresAt?: Date | string | null
  paidAt?: Date | string | null
  cancelledAt?: Date | string | null
  confirmedAt?: Date | string | null
  concludedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TicketOrderUpdateInput = {
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  responsibleAdminId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTicketOrderStatusFieldUpdateOperationsInput | $Enums.TicketOrderStatus
  cardType?: Prisma.NullableEnumTicketOrderCardTypeFieldUpdateOperationsInput | $Enums.TicketOrderCardType | null
  cardCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  deckLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  materialCostCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  profitMarginPercent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  finalPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  paymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentQrCodeBase64?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentCopyPaste?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentExpiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paidAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  concludedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  guild?: Prisma.GuildUpdateOneRequiredWithoutTicketOrdersNestedInput
}

export type TicketOrderUncheckedUpdateInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  responsibleAdminId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTicketOrderStatusFieldUpdateOperationsInput | $Enums.TicketOrderStatus
  cardType?: Prisma.NullableEnumTicketOrderCardTypeFieldUpdateOperationsInput | $Enums.TicketOrderCardType | null
  cardCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  deckLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  materialCostCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  profitMarginPercent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  finalPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  paymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentQrCodeBase64?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentCopyPaste?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentExpiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paidAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  concludedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TicketOrderCreateManyInput = {
  oid?: string
  guildId: string
  channelId: string
  userId: string
  responsibleAdminId?: string | null
  status?: $Enums.TicketOrderStatus
  cardType?: $Enums.TicketOrderCardType | null
  cardCount?: number | null
  deckLink?: string | null
  sheetCount?: number | null
  materialCostCents?: number | null
  profitMarginPercent?: number | null
  finalPriceCents?: number | null
  paymentId?: string | null
  paymentMessageId?: string | null
  paymentStatus?: string | null
  paymentQrCodeBase64?: string | null
  paymentCopyPaste?: string | null
  paymentExpiresAt?: Date | string | null
  paidAt?: Date | string | null
  cancelledAt?: Date | string | null
  confirmedAt?: Date | string | null
  concludedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TicketOrderUpdateManyMutationInput = {
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  responsibleAdminId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTicketOrderStatusFieldUpdateOperationsInput | $Enums.TicketOrderStatus
  cardType?: Prisma.NullableEnumTicketOrderCardTypeFieldUpdateOperationsInput | $Enums.TicketOrderCardType | null
  cardCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  deckLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  materialCostCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  profitMarginPercent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  finalPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  paymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentQrCodeBase64?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentCopyPaste?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentExpiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paidAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  concludedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TicketOrderUncheckedUpdateManyInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  responsibleAdminId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTicketOrderStatusFieldUpdateOperationsInput | $Enums.TicketOrderStatus
  cardType?: Prisma.NullableEnumTicketOrderCardTypeFieldUpdateOperationsInput | $Enums.TicketOrderCardType | null
  cardCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  deckLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  materialCostCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  profitMarginPercent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  finalPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  paymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentQrCodeBase64?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentCopyPaste?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentExpiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paidAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  concludedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TicketOrderListRelationFilter = {
  every?: Prisma.TicketOrderWhereInput
  some?: Prisma.TicketOrderWhereInput
  none?: Prisma.TicketOrderWhereInput
}

export type TicketOrderOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TicketOrderCountOrderByAggregateInput = {
  oid?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  responsibleAdminId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  cardType?: Prisma.SortOrder
  cardCount?: Prisma.SortOrder
  deckLink?: Prisma.SortOrder
  sheetCount?: Prisma.SortOrder
  materialCostCents?: Prisma.SortOrder
  profitMarginPercent?: Prisma.SortOrder
  finalPriceCents?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  paymentMessageId?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  paymentQrCodeBase64?: Prisma.SortOrder
  paymentCopyPaste?: Prisma.SortOrder
  paymentExpiresAt?: Prisma.SortOrder
  paidAt?: Prisma.SortOrder
  cancelledAt?: Prisma.SortOrder
  confirmedAt?: Prisma.SortOrder
  concludedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TicketOrderAvgOrderByAggregateInput = {
  cardCount?: Prisma.SortOrder
  sheetCount?: Prisma.SortOrder
  materialCostCents?: Prisma.SortOrder
  profitMarginPercent?: Prisma.SortOrder
  finalPriceCents?: Prisma.SortOrder
}

export type TicketOrderMaxOrderByAggregateInput = {
  oid?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  responsibleAdminId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  cardType?: Prisma.SortOrder
  cardCount?: Prisma.SortOrder
  deckLink?: Prisma.SortOrder
  sheetCount?: Prisma.SortOrder
  materialCostCents?: Prisma.SortOrder
  profitMarginPercent?: Prisma.SortOrder
  finalPriceCents?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  paymentMessageId?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  paymentQrCodeBase64?: Prisma.SortOrder
  paymentCopyPaste?: Prisma.SortOrder
  paymentExpiresAt?: Prisma.SortOrder
  paidAt?: Prisma.SortOrder
  cancelledAt?: Prisma.SortOrder
  confirmedAt?: Prisma.SortOrder
  concludedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TicketOrderMinOrderByAggregateInput = {
  oid?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  responsibleAdminId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  cardType?: Prisma.SortOrder
  cardCount?: Prisma.SortOrder
  deckLink?: Prisma.SortOrder
  sheetCount?: Prisma.SortOrder
  materialCostCents?: Prisma.SortOrder
  profitMarginPercent?: Prisma.SortOrder
  finalPriceCents?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  paymentMessageId?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  paymentQrCodeBase64?: Prisma.SortOrder
  paymentCopyPaste?: Prisma.SortOrder
  paymentExpiresAt?: Prisma.SortOrder
  paidAt?: Prisma.SortOrder
  cancelledAt?: Prisma.SortOrder
  confirmedAt?: Prisma.SortOrder
  concludedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TicketOrderSumOrderByAggregateInput = {
  cardCount?: Prisma.SortOrder
  sheetCount?: Prisma.SortOrder
  materialCostCents?: Prisma.SortOrder
  profitMarginPercent?: Prisma.SortOrder
  finalPriceCents?: Prisma.SortOrder
}

export type TicketOrderCreateNestedManyWithoutGuildInput = {
  create?: Prisma.XOR<Prisma.TicketOrderCreateWithoutGuildInput, Prisma.TicketOrderUncheckedCreateWithoutGuildInput> | Prisma.TicketOrderCreateWithoutGuildInput[] | Prisma.TicketOrderUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.TicketOrderCreateOrConnectWithoutGuildInput | Prisma.TicketOrderCreateOrConnectWithoutGuildInput[]
  createMany?: Prisma.TicketOrderCreateManyGuildInputEnvelope
  connect?: Prisma.TicketOrderWhereUniqueInput | Prisma.TicketOrderWhereUniqueInput[]
}

export type TicketOrderUncheckedCreateNestedManyWithoutGuildInput = {
  create?: Prisma.XOR<Prisma.TicketOrderCreateWithoutGuildInput, Prisma.TicketOrderUncheckedCreateWithoutGuildInput> | Prisma.TicketOrderCreateWithoutGuildInput[] | Prisma.TicketOrderUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.TicketOrderCreateOrConnectWithoutGuildInput | Prisma.TicketOrderCreateOrConnectWithoutGuildInput[]
  createMany?: Prisma.TicketOrderCreateManyGuildInputEnvelope
  connect?: Prisma.TicketOrderWhereUniqueInput | Prisma.TicketOrderWhereUniqueInput[]
}

export type TicketOrderUpdateManyWithoutGuildNestedInput = {
  create?: Prisma.XOR<Prisma.TicketOrderCreateWithoutGuildInput, Prisma.TicketOrderUncheckedCreateWithoutGuildInput> | Prisma.TicketOrderCreateWithoutGuildInput[] | Prisma.TicketOrderUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.TicketOrderCreateOrConnectWithoutGuildInput | Prisma.TicketOrderCreateOrConnectWithoutGuildInput[]
  upsert?: Prisma.TicketOrderUpsertWithWhereUniqueWithoutGuildInput | Prisma.TicketOrderUpsertWithWhereUniqueWithoutGuildInput[]
  createMany?: Prisma.TicketOrderCreateManyGuildInputEnvelope
  set?: Prisma.TicketOrderWhereUniqueInput | Prisma.TicketOrderWhereUniqueInput[]
  disconnect?: Prisma.TicketOrderWhereUniqueInput | Prisma.TicketOrderWhereUniqueInput[]
  delete?: Prisma.TicketOrderWhereUniqueInput | Prisma.TicketOrderWhereUniqueInput[]
  connect?: Prisma.TicketOrderWhereUniqueInput | Prisma.TicketOrderWhereUniqueInput[]
  update?: Prisma.TicketOrderUpdateWithWhereUniqueWithoutGuildInput | Prisma.TicketOrderUpdateWithWhereUniqueWithoutGuildInput[]
  updateMany?: Prisma.TicketOrderUpdateManyWithWhereWithoutGuildInput | Prisma.TicketOrderUpdateManyWithWhereWithoutGuildInput[]
  deleteMany?: Prisma.TicketOrderScalarWhereInput | Prisma.TicketOrderScalarWhereInput[]
}

export type TicketOrderUncheckedUpdateManyWithoutGuildNestedInput = {
  create?: Prisma.XOR<Prisma.TicketOrderCreateWithoutGuildInput, Prisma.TicketOrderUncheckedCreateWithoutGuildInput> | Prisma.TicketOrderCreateWithoutGuildInput[] | Prisma.TicketOrderUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.TicketOrderCreateOrConnectWithoutGuildInput | Prisma.TicketOrderCreateOrConnectWithoutGuildInput[]
  upsert?: Prisma.TicketOrderUpsertWithWhereUniqueWithoutGuildInput | Prisma.TicketOrderUpsertWithWhereUniqueWithoutGuildInput[]
  createMany?: Prisma.TicketOrderCreateManyGuildInputEnvelope
  set?: Prisma.TicketOrderWhereUniqueInput | Prisma.TicketOrderWhereUniqueInput[]
  disconnect?: Prisma.TicketOrderWhereUniqueInput | Prisma.TicketOrderWhereUniqueInput[]
  delete?: Prisma.TicketOrderWhereUniqueInput | Prisma.TicketOrderWhereUniqueInput[]
  connect?: Prisma.TicketOrderWhereUniqueInput | Prisma.TicketOrderWhereUniqueInput[]
  update?: Prisma.TicketOrderUpdateWithWhereUniqueWithoutGuildInput | Prisma.TicketOrderUpdateWithWhereUniqueWithoutGuildInput[]
  updateMany?: Prisma.TicketOrderUpdateManyWithWhereWithoutGuildInput | Prisma.TicketOrderUpdateManyWithWhereWithoutGuildInput[]
  deleteMany?: Prisma.TicketOrderScalarWhereInput | Prisma.TicketOrderScalarWhereInput[]
}

export type EnumTicketOrderStatusFieldUpdateOperationsInput = {
  set?: $Enums.TicketOrderStatus
}

export type NullableEnumTicketOrderCardTypeFieldUpdateOperationsInput = {
  set?: $Enums.TicketOrderCardType | null
  unset?: boolean
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
  unset?: boolean
}

export type TicketOrderCreateWithoutGuildInput = {
  oid?: string
  channelId: string
  userId: string
  responsibleAdminId?: string | null
  status?: $Enums.TicketOrderStatus
  cardType?: $Enums.TicketOrderCardType | null
  cardCount?: number | null
  deckLink?: string | null
  sheetCount?: number | null
  materialCostCents?: number | null
  profitMarginPercent?: number | null
  finalPriceCents?: number | null
  paymentId?: string | null
  paymentMessageId?: string | null
  paymentStatus?: string | null
  paymentQrCodeBase64?: string | null
  paymentCopyPaste?: string | null
  paymentExpiresAt?: Date | string | null
  paidAt?: Date | string | null
  cancelledAt?: Date | string | null
  confirmedAt?: Date | string | null
  concludedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TicketOrderUncheckedCreateWithoutGuildInput = {
  oid?: string
  channelId: string
  userId: string
  responsibleAdminId?: string | null
  status?: $Enums.TicketOrderStatus
  cardType?: $Enums.TicketOrderCardType | null
  cardCount?: number | null
  deckLink?: string | null
  sheetCount?: number | null
  materialCostCents?: number | null
  profitMarginPercent?: number | null
  finalPriceCents?: number | null
  paymentId?: string | null
  paymentMessageId?: string | null
  paymentStatus?: string | null
  paymentQrCodeBase64?: string | null
  paymentCopyPaste?: string | null
  paymentExpiresAt?: Date | string | null
  paidAt?: Date | string | null
  cancelledAt?: Date | string | null
  confirmedAt?: Date | string | null
  concludedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TicketOrderCreateOrConnectWithoutGuildInput = {
  where: Prisma.TicketOrderWhereUniqueInput
  create: Prisma.XOR<Prisma.TicketOrderCreateWithoutGuildInput, Prisma.TicketOrderUncheckedCreateWithoutGuildInput>
}

export type TicketOrderCreateManyGuildInputEnvelope = {
  data: Prisma.TicketOrderCreateManyGuildInput | Prisma.TicketOrderCreateManyGuildInput[]
}

export type TicketOrderUpsertWithWhereUniqueWithoutGuildInput = {
  where: Prisma.TicketOrderWhereUniqueInput
  update: Prisma.XOR<Prisma.TicketOrderUpdateWithoutGuildInput, Prisma.TicketOrderUncheckedUpdateWithoutGuildInput>
  create: Prisma.XOR<Prisma.TicketOrderCreateWithoutGuildInput, Prisma.TicketOrderUncheckedCreateWithoutGuildInput>
}

export type TicketOrderUpdateWithWhereUniqueWithoutGuildInput = {
  where: Prisma.TicketOrderWhereUniqueInput
  data: Prisma.XOR<Prisma.TicketOrderUpdateWithoutGuildInput, Prisma.TicketOrderUncheckedUpdateWithoutGuildInput>
}

export type TicketOrderUpdateManyWithWhereWithoutGuildInput = {
  where: Prisma.TicketOrderScalarWhereInput
  data: Prisma.XOR<Prisma.TicketOrderUpdateManyMutationInput, Prisma.TicketOrderUncheckedUpdateManyWithoutGuildInput>
}

export type TicketOrderScalarWhereInput = {
  AND?: Prisma.TicketOrderScalarWhereInput | Prisma.TicketOrderScalarWhereInput[]
  OR?: Prisma.TicketOrderScalarWhereInput[]
  NOT?: Prisma.TicketOrderScalarWhereInput | Prisma.TicketOrderScalarWhereInput[]
  oid?: Prisma.StringFilter<"TicketOrder"> | string
  guildId?: Prisma.StringFilter<"TicketOrder"> | string
  channelId?: Prisma.StringFilter<"TicketOrder"> | string
  userId?: Prisma.StringFilter<"TicketOrder"> | string
  responsibleAdminId?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  status?: Prisma.EnumTicketOrderStatusFilter<"TicketOrder"> | $Enums.TicketOrderStatus
  cardType?: Prisma.EnumTicketOrderCardTypeNullableFilter<"TicketOrder"> | $Enums.TicketOrderCardType | null
  cardCount?: Prisma.IntNullableFilter<"TicketOrder"> | number | null
  deckLink?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  sheetCount?: Prisma.IntNullableFilter<"TicketOrder"> | number | null
  materialCostCents?: Prisma.IntNullableFilter<"TicketOrder"> | number | null
  profitMarginPercent?: Prisma.IntNullableFilter<"TicketOrder"> | number | null
  finalPriceCents?: Prisma.IntNullableFilter<"TicketOrder"> | number | null
  paymentId?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  paymentMessageId?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  paymentStatus?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  paymentQrCodeBase64?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  paymentCopyPaste?: Prisma.StringNullableFilter<"TicketOrder"> | string | null
  paymentExpiresAt?: Prisma.DateTimeNullableFilter<"TicketOrder"> | Date | string | null
  paidAt?: Prisma.DateTimeNullableFilter<"TicketOrder"> | Date | string | null
  cancelledAt?: Prisma.DateTimeNullableFilter<"TicketOrder"> | Date | string | null
  confirmedAt?: Prisma.DateTimeNullableFilter<"TicketOrder"> | Date | string | null
  concludedAt?: Prisma.DateTimeNullableFilter<"TicketOrder"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"TicketOrder"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TicketOrder"> | Date | string
}

export type TicketOrderCreateManyGuildInput = {
  oid?: string
  channelId: string
  userId: string
  responsibleAdminId?: string | null
  status?: $Enums.TicketOrderStatus
  cardType?: $Enums.TicketOrderCardType | null
  cardCount?: number | null
  deckLink?: string | null
  sheetCount?: number | null
  materialCostCents?: number | null
  profitMarginPercent?: number | null
  finalPriceCents?: number | null
  paymentId?: string | null
  paymentMessageId?: string | null
  paymentStatus?: string | null
  paymentQrCodeBase64?: string | null
  paymentCopyPaste?: string | null
  paymentExpiresAt?: Date | string | null
  paidAt?: Date | string | null
  cancelledAt?: Date | string | null
  confirmedAt?: Date | string | null
  concludedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TicketOrderUpdateWithoutGuildInput = {
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  responsibleAdminId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTicketOrderStatusFieldUpdateOperationsInput | $Enums.TicketOrderStatus
  cardType?: Prisma.NullableEnumTicketOrderCardTypeFieldUpdateOperationsInput | $Enums.TicketOrderCardType | null
  cardCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  deckLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  materialCostCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  profitMarginPercent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  finalPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  paymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentQrCodeBase64?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentCopyPaste?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentExpiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paidAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  concludedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TicketOrderUncheckedUpdateWithoutGuildInput = {
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  responsibleAdminId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTicketOrderStatusFieldUpdateOperationsInput | $Enums.TicketOrderStatus
  cardType?: Prisma.NullableEnumTicketOrderCardTypeFieldUpdateOperationsInput | $Enums.TicketOrderCardType | null
  cardCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  deckLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  materialCostCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  profitMarginPercent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  finalPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  paymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentQrCodeBase64?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentCopyPaste?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentExpiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paidAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  concludedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TicketOrderUncheckedUpdateManyWithoutGuildInput = {
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  responsibleAdminId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTicketOrderStatusFieldUpdateOperationsInput | $Enums.TicketOrderStatus
  cardType?: Prisma.NullableEnumTicketOrderCardTypeFieldUpdateOperationsInput | $Enums.TicketOrderCardType | null
  cardCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  deckLink?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sheetCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  materialCostCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  profitMarginPercent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  finalPriceCents?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  paymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentQrCodeBase64?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentCopyPaste?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentExpiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paidAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  concludedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TicketOrderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  oid?: boolean
  guildId?: boolean
  channelId?: boolean
  userId?: boolean
  responsibleAdminId?: boolean
  status?: boolean
  cardType?: boolean
  cardCount?: boolean
  deckLink?: boolean
  sheetCount?: boolean
  materialCostCents?: boolean
  profitMarginPercent?: boolean
  finalPriceCents?: boolean
  paymentId?: boolean
  paymentMessageId?: boolean
  paymentStatus?: boolean
  paymentQrCodeBase64?: boolean
  paymentCopyPaste?: boolean
  paymentExpiresAt?: boolean
  paidAt?: boolean
  cancelledAt?: boolean
  confirmedAt?: boolean
  concludedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticketOrder"]>



export type TicketOrderSelectScalar = {
  oid?: boolean
  guildId?: boolean
  channelId?: boolean
  userId?: boolean
  responsibleAdminId?: boolean
  status?: boolean
  cardType?: boolean
  cardCount?: boolean
  deckLink?: boolean
  sheetCount?: boolean
  materialCostCents?: boolean
  profitMarginPercent?: boolean
  finalPriceCents?: boolean
  paymentId?: boolean
  paymentMessageId?: boolean
  paymentStatus?: boolean
  paymentQrCodeBase64?: boolean
  paymentCopyPaste?: boolean
  paymentExpiresAt?: boolean
  paidAt?: boolean
  cancelledAt?: boolean
  confirmedAt?: boolean
  concludedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TicketOrderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"oid" | "guildId" | "channelId" | "userId" | "responsibleAdminId" | "status" | "cardType" | "cardCount" | "deckLink" | "sheetCount" | "materialCostCents" | "profitMarginPercent" | "finalPriceCents" | "paymentId" | "paymentMessageId" | "paymentStatus" | "paymentQrCodeBase64" | "paymentCopyPaste" | "paymentExpiresAt" | "paidAt" | "cancelledAt" | "confirmedAt" | "concludedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["ticketOrder"]>
export type TicketOrderInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
}

export type $TicketOrderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TicketOrder"
  objects: {
    guild: Prisma.$GuildPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    oid: string
    guildId: string
    channelId: string
    userId: string
    responsibleAdminId: string | null
    status: $Enums.TicketOrderStatus
    cardType: $Enums.TicketOrderCardType | null
    cardCount: number | null
    deckLink: string | null
    sheetCount: number | null
    materialCostCents: number | null
    profitMarginPercent: number | null
    finalPriceCents: number | null
    paymentId: string | null
    paymentMessageId: string | null
    paymentStatus: string | null
    paymentQrCodeBase64: string | null
    paymentCopyPaste: string | null
    paymentExpiresAt: Date | null
    paidAt: Date | null
    cancelledAt: Date | null
    confirmedAt: Date | null
    concludedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["ticketOrder"]>
  composites: {}
}

export type TicketOrderGetPayload<S extends boolean | null | undefined | TicketOrderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TicketOrderPayload, S>

export type TicketOrderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TicketOrderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TicketOrderCountAggregateInputType | true
  }

export interface TicketOrderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TicketOrder'], meta: { name: 'TicketOrder' } }
  /**
   * Find zero or one TicketOrder that matches the filter.
   * @param {TicketOrderFindUniqueArgs} args - Arguments to find a TicketOrder
   * @example
   * // Get one TicketOrder
   * const ticketOrder = await prisma.ticketOrder.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TicketOrderFindUniqueArgs>(args: Prisma.SelectSubset<T, TicketOrderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TicketOrderClient<runtime.Types.Result.GetResult<Prisma.$TicketOrderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TicketOrder that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TicketOrderFindUniqueOrThrowArgs} args - Arguments to find a TicketOrder
   * @example
   * // Get one TicketOrder
   * const ticketOrder = await prisma.ticketOrder.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TicketOrderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TicketOrderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketOrderClient<runtime.Types.Result.GetResult<Prisma.$TicketOrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TicketOrder that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketOrderFindFirstArgs} args - Arguments to find a TicketOrder
   * @example
   * // Get one TicketOrder
   * const ticketOrder = await prisma.ticketOrder.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TicketOrderFindFirstArgs>(args?: Prisma.SelectSubset<T, TicketOrderFindFirstArgs<ExtArgs>>): Prisma.Prisma__TicketOrderClient<runtime.Types.Result.GetResult<Prisma.$TicketOrderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TicketOrder that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketOrderFindFirstOrThrowArgs} args - Arguments to find a TicketOrder
   * @example
   * // Get one TicketOrder
   * const ticketOrder = await prisma.ticketOrder.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TicketOrderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TicketOrderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketOrderClient<runtime.Types.Result.GetResult<Prisma.$TicketOrderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TicketOrders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketOrderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TicketOrders
   * const ticketOrders = await prisma.ticketOrder.findMany()
   * 
   * // Get first 10 TicketOrders
   * const ticketOrders = await prisma.ticketOrder.findMany({ take: 10 })
   * 
   * // Only select the `oid`
   * const ticketOrderWithOidOnly = await prisma.ticketOrder.findMany({ select: { oid: true } })
   * 
   */
  findMany<T extends TicketOrderFindManyArgs>(args?: Prisma.SelectSubset<T, TicketOrderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketOrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TicketOrder.
   * @param {TicketOrderCreateArgs} args - Arguments to create a TicketOrder.
   * @example
   * // Create one TicketOrder
   * const TicketOrder = await prisma.ticketOrder.create({
   *   data: {
   *     // ... data to create a TicketOrder
   *   }
   * })
   * 
   */
  create<T extends TicketOrderCreateArgs>(args: Prisma.SelectSubset<T, TicketOrderCreateArgs<ExtArgs>>): Prisma.Prisma__TicketOrderClient<runtime.Types.Result.GetResult<Prisma.$TicketOrderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TicketOrders.
   * @param {TicketOrderCreateManyArgs} args - Arguments to create many TicketOrders.
   * @example
   * // Create many TicketOrders
   * const ticketOrder = await prisma.ticketOrder.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TicketOrderCreateManyArgs>(args?: Prisma.SelectSubset<T, TicketOrderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a TicketOrder.
   * @param {TicketOrderDeleteArgs} args - Arguments to delete one TicketOrder.
   * @example
   * // Delete one TicketOrder
   * const TicketOrder = await prisma.ticketOrder.delete({
   *   where: {
   *     // ... filter to delete one TicketOrder
   *   }
   * })
   * 
   */
  delete<T extends TicketOrderDeleteArgs>(args: Prisma.SelectSubset<T, TicketOrderDeleteArgs<ExtArgs>>): Prisma.Prisma__TicketOrderClient<runtime.Types.Result.GetResult<Prisma.$TicketOrderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TicketOrder.
   * @param {TicketOrderUpdateArgs} args - Arguments to update one TicketOrder.
   * @example
   * // Update one TicketOrder
   * const ticketOrder = await prisma.ticketOrder.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TicketOrderUpdateArgs>(args: Prisma.SelectSubset<T, TicketOrderUpdateArgs<ExtArgs>>): Prisma.Prisma__TicketOrderClient<runtime.Types.Result.GetResult<Prisma.$TicketOrderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TicketOrders.
   * @param {TicketOrderDeleteManyArgs} args - Arguments to filter TicketOrders to delete.
   * @example
   * // Delete a few TicketOrders
   * const { count } = await prisma.ticketOrder.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TicketOrderDeleteManyArgs>(args?: Prisma.SelectSubset<T, TicketOrderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TicketOrders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketOrderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TicketOrders
   * const ticketOrder = await prisma.ticketOrder.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TicketOrderUpdateManyArgs>(args: Prisma.SelectSubset<T, TicketOrderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one TicketOrder.
   * @param {TicketOrderUpsertArgs} args - Arguments to update or create a TicketOrder.
   * @example
   * // Update or create a TicketOrder
   * const ticketOrder = await prisma.ticketOrder.upsert({
   *   create: {
   *     // ... data to create a TicketOrder
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TicketOrder we want to update
   *   }
   * })
   */
  upsert<T extends TicketOrderUpsertArgs>(args: Prisma.SelectSubset<T, TicketOrderUpsertArgs<ExtArgs>>): Prisma.Prisma__TicketOrderClient<runtime.Types.Result.GetResult<Prisma.$TicketOrderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TicketOrders that matches the filter.
   * @param {TicketOrderFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const ticketOrder = await prisma.ticketOrder.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.TicketOrderFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>

  /**
   * Perform aggregation operations on a TicketOrder.
   * @param {TicketOrderAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const ticketOrder = await prisma.ticketOrder.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.TicketOrderAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>


  /**
   * Count the number of TicketOrders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketOrderCountArgs} args - Arguments to filter TicketOrders to count.
   * @example
   * // Count the number of TicketOrders
   * const count = await prisma.ticketOrder.count({
   *   where: {
   *     // ... the filter for the TicketOrders we want to count
   *   }
   * })
  **/
  count<T extends TicketOrderCountArgs>(
    args?: Prisma.Subset<T, TicketOrderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TicketOrderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TicketOrder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketOrderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TicketOrderAggregateArgs>(args: Prisma.Subset<T, TicketOrderAggregateArgs>): Prisma.PrismaPromise<GetTicketOrderAggregateType<T>>

  /**
   * Group by TicketOrder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketOrderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TicketOrderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TicketOrderGroupByArgs['orderBy'] }
      : { orderBy?: TicketOrderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TicketOrderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTicketOrderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TicketOrder model
 */
readonly fields: TicketOrderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TicketOrder.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TicketOrderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  guild<T extends Prisma.GuildDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GuildDefaultArgs<ExtArgs>>): Prisma.Prisma__GuildClient<runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TicketOrder model
 */
export interface TicketOrderFieldRefs {
  readonly oid: Prisma.FieldRef<"TicketOrder", 'String'>
  readonly guildId: Prisma.FieldRef<"TicketOrder", 'String'>
  readonly channelId: Prisma.FieldRef<"TicketOrder", 'String'>
  readonly userId: Prisma.FieldRef<"TicketOrder", 'String'>
  readonly responsibleAdminId: Prisma.FieldRef<"TicketOrder", 'String'>
  readonly status: Prisma.FieldRef<"TicketOrder", 'TicketOrderStatus'>
  readonly cardType: Prisma.FieldRef<"TicketOrder", 'TicketOrderCardType'>
  readonly cardCount: Prisma.FieldRef<"TicketOrder", 'Int'>
  readonly deckLink: Prisma.FieldRef<"TicketOrder", 'String'>
  readonly sheetCount: Prisma.FieldRef<"TicketOrder", 'Int'>
  readonly materialCostCents: Prisma.FieldRef<"TicketOrder", 'Int'>
  readonly profitMarginPercent: Prisma.FieldRef<"TicketOrder", 'Int'>
  readonly finalPriceCents: Prisma.FieldRef<"TicketOrder", 'Int'>
  readonly paymentId: Prisma.FieldRef<"TicketOrder", 'String'>
  readonly paymentMessageId: Prisma.FieldRef<"TicketOrder", 'String'>
  readonly paymentStatus: Prisma.FieldRef<"TicketOrder", 'String'>
  readonly paymentQrCodeBase64: Prisma.FieldRef<"TicketOrder", 'String'>
  readonly paymentCopyPaste: Prisma.FieldRef<"TicketOrder", 'String'>
  readonly paymentExpiresAt: Prisma.FieldRef<"TicketOrder", 'DateTime'>
  readonly paidAt: Prisma.FieldRef<"TicketOrder", 'DateTime'>
  readonly cancelledAt: Prisma.FieldRef<"TicketOrder", 'DateTime'>
  readonly confirmedAt: Prisma.FieldRef<"TicketOrder", 'DateTime'>
  readonly concludedAt: Prisma.FieldRef<"TicketOrder", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"TicketOrder", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TicketOrder", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TicketOrder findUnique
 */
export type TicketOrderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketOrder
   */
  select?: Prisma.TicketOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketOrder
   */
  omit?: Prisma.TicketOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketOrderInclude<ExtArgs> | null
  /**
   * Filter, which TicketOrder to fetch.
   */
  where: Prisma.TicketOrderWhereUniqueInput
}

/**
 * TicketOrder findUniqueOrThrow
 */
export type TicketOrderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketOrder
   */
  select?: Prisma.TicketOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketOrder
   */
  omit?: Prisma.TicketOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketOrderInclude<ExtArgs> | null
  /**
   * Filter, which TicketOrder to fetch.
   */
  where: Prisma.TicketOrderWhereUniqueInput
}

/**
 * TicketOrder findFirst
 */
export type TicketOrderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketOrder
   */
  select?: Prisma.TicketOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketOrder
   */
  omit?: Prisma.TicketOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketOrderInclude<ExtArgs> | null
  /**
   * Filter, which TicketOrder to fetch.
   */
  where?: Prisma.TicketOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketOrders to fetch.
   */
  orderBy?: Prisma.TicketOrderOrderByWithRelationInput | Prisma.TicketOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TicketOrders.
   */
  cursor?: Prisma.TicketOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TicketOrders.
   */
  distinct?: Prisma.TicketOrderScalarFieldEnum | Prisma.TicketOrderScalarFieldEnum[]
}

/**
 * TicketOrder findFirstOrThrow
 */
export type TicketOrderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketOrder
   */
  select?: Prisma.TicketOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketOrder
   */
  omit?: Prisma.TicketOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketOrderInclude<ExtArgs> | null
  /**
   * Filter, which TicketOrder to fetch.
   */
  where?: Prisma.TicketOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketOrders to fetch.
   */
  orderBy?: Prisma.TicketOrderOrderByWithRelationInput | Prisma.TicketOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TicketOrders.
   */
  cursor?: Prisma.TicketOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TicketOrders.
   */
  distinct?: Prisma.TicketOrderScalarFieldEnum | Prisma.TicketOrderScalarFieldEnum[]
}

/**
 * TicketOrder findMany
 */
export type TicketOrderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketOrder
   */
  select?: Prisma.TicketOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketOrder
   */
  omit?: Prisma.TicketOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketOrderInclude<ExtArgs> | null
  /**
   * Filter, which TicketOrders to fetch.
   */
  where?: Prisma.TicketOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketOrders to fetch.
   */
  orderBy?: Prisma.TicketOrderOrderByWithRelationInput | Prisma.TicketOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TicketOrders.
   */
  cursor?: Prisma.TicketOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketOrders.
   */
  skip?: number
  distinct?: Prisma.TicketOrderScalarFieldEnum | Prisma.TicketOrderScalarFieldEnum[]
}

/**
 * TicketOrder create
 */
export type TicketOrderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketOrder
   */
  select?: Prisma.TicketOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketOrder
   */
  omit?: Prisma.TicketOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketOrderInclude<ExtArgs> | null
  /**
   * The data needed to create a TicketOrder.
   */
  data: Prisma.XOR<Prisma.TicketOrderCreateInput, Prisma.TicketOrderUncheckedCreateInput>
}

/**
 * TicketOrder createMany
 */
export type TicketOrderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TicketOrders.
   */
  data: Prisma.TicketOrderCreateManyInput | Prisma.TicketOrderCreateManyInput[]
}

/**
 * TicketOrder update
 */
export type TicketOrderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketOrder
   */
  select?: Prisma.TicketOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketOrder
   */
  omit?: Prisma.TicketOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketOrderInclude<ExtArgs> | null
  /**
   * The data needed to update a TicketOrder.
   */
  data: Prisma.XOR<Prisma.TicketOrderUpdateInput, Prisma.TicketOrderUncheckedUpdateInput>
  /**
   * Choose, which TicketOrder to update.
   */
  where: Prisma.TicketOrderWhereUniqueInput
}

/**
 * TicketOrder updateMany
 */
export type TicketOrderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TicketOrders.
   */
  data: Prisma.XOR<Prisma.TicketOrderUpdateManyMutationInput, Prisma.TicketOrderUncheckedUpdateManyInput>
  /**
   * Filter which TicketOrders to update
   */
  where?: Prisma.TicketOrderWhereInput
  /**
   * Limit how many TicketOrders to update.
   */
  limit?: number
}

/**
 * TicketOrder upsert
 */
export type TicketOrderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketOrder
   */
  select?: Prisma.TicketOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketOrder
   */
  omit?: Prisma.TicketOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketOrderInclude<ExtArgs> | null
  /**
   * The filter to search for the TicketOrder to update in case it exists.
   */
  where: Prisma.TicketOrderWhereUniqueInput
  /**
   * In case the TicketOrder found by the `where` argument doesn't exist, create a new TicketOrder with this data.
   */
  create: Prisma.XOR<Prisma.TicketOrderCreateInput, Prisma.TicketOrderUncheckedCreateInput>
  /**
   * In case the TicketOrder was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TicketOrderUpdateInput, Prisma.TicketOrderUncheckedUpdateInput>
}

/**
 * TicketOrder delete
 */
export type TicketOrderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketOrder
   */
  select?: Prisma.TicketOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketOrder
   */
  omit?: Prisma.TicketOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketOrderInclude<ExtArgs> | null
  /**
   * Filter which TicketOrder to delete.
   */
  where: Prisma.TicketOrderWhereUniqueInput
}

/**
 * TicketOrder deleteMany
 */
export type TicketOrderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TicketOrders to delete
   */
  where?: Prisma.TicketOrderWhereInput
  /**
   * Limit how many TicketOrders to delete.
   */
  limit?: number
}

/**
 * TicketOrder findRaw
 */
export type TicketOrderFindRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * TicketOrder aggregateRaw
 */
export type TicketOrderAggregateRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[]
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * TicketOrder without action
 */
export type TicketOrderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketOrder
   */
  select?: Prisma.TicketOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketOrder
   */
  omit?: Prisma.TicketOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketOrderInclude<ExtArgs> | null
}
