
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `TicketHistory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TicketHistory
 * 
 */
export type TicketHistoryModel = runtime.Types.Result.DefaultSelection<Prisma.$TicketHistoryPayload>

export type AggregateTicketHistory = {
  _count: TicketHistoryCountAggregateOutputType | null
  _avg: TicketHistoryAvgAggregateOutputType | null
  _sum: TicketHistorySumAggregateOutputType | null
  _min: TicketHistoryMinAggregateOutputType | null
  _max: TicketHistoryMaxAggregateOutputType | null
}

export type TicketHistoryAvgAggregateOutputType = {
  id: number | null
  ticketId: number | null
}

export type TicketHistorySumAggregateOutputType = {
  id: number | null
  ticketId: number | null
}

export type TicketHistoryMinAggregateOutputType = {
  id: number | null
  ticketId: number | null
  oldStatus: $Enums.TicketStatus | null
  newStatus: $Enums.TicketStatus | null
  oldCategoryId: string | null
  newCategoryId: string | null
  changedBy: string | null
  changedAt: Date | null
  notes: string | null
}

export type TicketHistoryMaxAggregateOutputType = {
  id: number | null
  ticketId: number | null
  oldStatus: $Enums.TicketStatus | null
  newStatus: $Enums.TicketStatus | null
  oldCategoryId: string | null
  newCategoryId: string | null
  changedBy: string | null
  changedAt: Date | null
  notes: string | null
}

export type TicketHistoryCountAggregateOutputType = {
  id: number
  ticketId: number
  oldStatus: number
  newStatus: number
  oldCategoryId: number
  newCategoryId: number
  changedBy: number
  changedAt: number
  notes: number
  _all: number
}


export type TicketHistoryAvgAggregateInputType = {
  id?: true
  ticketId?: true
}

export type TicketHistorySumAggregateInputType = {
  id?: true
  ticketId?: true
}

export type TicketHistoryMinAggregateInputType = {
  id?: true
  ticketId?: true
  oldStatus?: true
  newStatus?: true
  oldCategoryId?: true
  newCategoryId?: true
  changedBy?: true
  changedAt?: true
  notes?: true
}

export type TicketHistoryMaxAggregateInputType = {
  id?: true
  ticketId?: true
  oldStatus?: true
  newStatus?: true
  oldCategoryId?: true
  newCategoryId?: true
  changedBy?: true
  changedAt?: true
  notes?: true
}

export type TicketHistoryCountAggregateInputType = {
  id?: true
  ticketId?: true
  oldStatus?: true
  newStatus?: true
  oldCategoryId?: true
  newCategoryId?: true
  changedBy?: true
  changedAt?: true
  notes?: true
  _all?: true
}

export type TicketHistoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TicketHistory to aggregate.
   */
  where?: Prisma.TicketHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketHistories to fetch.
   */
  orderBy?: Prisma.TicketHistoryOrderByWithRelationInput | Prisma.TicketHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TicketHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TicketHistories
  **/
  _count?: true | TicketHistoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TicketHistoryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TicketHistorySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TicketHistoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TicketHistoryMaxAggregateInputType
}

export type GetTicketHistoryAggregateType<T extends TicketHistoryAggregateArgs> = {
      [P in keyof T & keyof AggregateTicketHistory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTicketHistory[P]>
    : Prisma.GetScalarType<T[P], AggregateTicketHistory[P]>
}




export type TicketHistoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TicketHistoryWhereInput
  orderBy?: Prisma.TicketHistoryOrderByWithAggregationInput | Prisma.TicketHistoryOrderByWithAggregationInput[]
  by: Prisma.TicketHistoryScalarFieldEnum[] | Prisma.TicketHistoryScalarFieldEnum
  having?: Prisma.TicketHistoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TicketHistoryCountAggregateInputType | true
  _avg?: TicketHistoryAvgAggregateInputType
  _sum?: TicketHistorySumAggregateInputType
  _min?: TicketHistoryMinAggregateInputType
  _max?: TicketHistoryMaxAggregateInputType
}

export type TicketHistoryGroupByOutputType = {
  id: number
  ticketId: number
  oldStatus: $Enums.TicketStatus | null
  newStatus: $Enums.TicketStatus
  oldCategoryId: string | null
  newCategoryId: string
  changedBy: string
  changedAt: Date
  notes: string | null
  _count: TicketHistoryCountAggregateOutputType | null
  _avg: TicketHistoryAvgAggregateOutputType | null
  _sum: TicketHistorySumAggregateOutputType | null
  _min: TicketHistoryMinAggregateOutputType | null
  _max: TicketHistoryMaxAggregateOutputType | null
}

type GetTicketHistoryGroupByPayload<T extends TicketHistoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TicketHistoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TicketHistoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TicketHistoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TicketHistoryGroupByOutputType[P]>
      }
    >
  >



export type TicketHistoryWhereInput = {
  AND?: Prisma.TicketHistoryWhereInput | Prisma.TicketHistoryWhereInput[]
  OR?: Prisma.TicketHistoryWhereInput[]
  NOT?: Prisma.TicketHistoryWhereInput | Prisma.TicketHistoryWhereInput[]
  id?: Prisma.IntFilter<"TicketHistory"> | number
  ticketId?: Prisma.IntFilter<"TicketHistory"> | number
  oldStatus?: Prisma.EnumTicketStatusNullableFilter<"TicketHistory"> | $Enums.TicketStatus | null
  newStatus?: Prisma.EnumTicketStatusFilter<"TicketHistory"> | $Enums.TicketStatus
  oldCategoryId?: Prisma.StringNullableFilter<"TicketHistory"> | string | null
  newCategoryId?: Prisma.StringFilter<"TicketHistory"> | string
  changedBy?: Prisma.StringFilter<"TicketHistory"> | string
  changedAt?: Prisma.DateTimeFilter<"TicketHistory"> | Date | string
  notes?: Prisma.StringNullableFilter<"TicketHistory"> | string | null
  ticket?: Prisma.XOR<Prisma.TicketScalarRelationFilter, Prisma.TicketWhereInput>
}

export type TicketHistoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
  oldStatus?: Prisma.SortOrderInput | Prisma.SortOrder
  newStatus?: Prisma.SortOrder
  oldCategoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  newCategoryId?: Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  changedAt?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  ticket?: Prisma.TicketOrderByWithRelationInput
}

export type TicketHistoryWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.TicketHistoryWhereInput | Prisma.TicketHistoryWhereInput[]
  OR?: Prisma.TicketHistoryWhereInput[]
  NOT?: Prisma.TicketHistoryWhereInput | Prisma.TicketHistoryWhereInput[]
  ticketId?: Prisma.IntFilter<"TicketHistory"> | number
  oldStatus?: Prisma.EnumTicketStatusNullableFilter<"TicketHistory"> | $Enums.TicketStatus | null
  newStatus?: Prisma.EnumTicketStatusFilter<"TicketHistory"> | $Enums.TicketStatus
  oldCategoryId?: Prisma.StringNullableFilter<"TicketHistory"> | string | null
  newCategoryId?: Prisma.StringFilter<"TicketHistory"> | string
  changedBy?: Prisma.StringFilter<"TicketHistory"> | string
  changedAt?: Prisma.DateTimeFilter<"TicketHistory"> | Date | string
  notes?: Prisma.StringNullableFilter<"TicketHistory"> | string | null
  ticket?: Prisma.XOR<Prisma.TicketScalarRelationFilter, Prisma.TicketWhereInput>
}, "id">

export type TicketHistoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
  oldStatus?: Prisma.SortOrderInput | Prisma.SortOrder
  newStatus?: Prisma.SortOrder
  oldCategoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  newCategoryId?: Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  changedAt?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TicketHistoryCountOrderByAggregateInput
  _avg?: Prisma.TicketHistoryAvgOrderByAggregateInput
  _max?: Prisma.TicketHistoryMaxOrderByAggregateInput
  _min?: Prisma.TicketHistoryMinOrderByAggregateInput
  _sum?: Prisma.TicketHistorySumOrderByAggregateInput
}

export type TicketHistoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.TicketHistoryScalarWhereWithAggregatesInput | Prisma.TicketHistoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.TicketHistoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TicketHistoryScalarWhereWithAggregatesInput | Prisma.TicketHistoryScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"TicketHistory"> | number
  ticketId?: Prisma.IntWithAggregatesFilter<"TicketHistory"> | number
  oldStatus?: Prisma.EnumTicketStatusNullableWithAggregatesFilter<"TicketHistory"> | $Enums.TicketStatus | null
  newStatus?: Prisma.EnumTicketStatusWithAggregatesFilter<"TicketHistory"> | $Enums.TicketStatus
  oldCategoryId?: Prisma.StringNullableWithAggregatesFilter<"TicketHistory"> | string | null
  newCategoryId?: Prisma.StringWithAggregatesFilter<"TicketHistory"> | string
  changedBy?: Prisma.StringWithAggregatesFilter<"TicketHistory"> | string
  changedAt?: Prisma.DateTimeWithAggregatesFilter<"TicketHistory"> | Date | string
  notes?: Prisma.StringNullableWithAggregatesFilter<"TicketHistory"> | string | null
}

export type TicketHistoryCreateInput = {
  oldStatus?: $Enums.TicketStatus | null
  newStatus: $Enums.TicketStatus
  oldCategoryId?: string | null
  newCategoryId: string
  changedBy: string
  changedAt?: Date | string
  notes?: string | null
  ticket: Prisma.TicketCreateNestedOneWithoutHistoryInput
}

export type TicketHistoryUncheckedCreateInput = {
  id?: number
  ticketId: number
  oldStatus?: $Enums.TicketStatus | null
  newStatus: $Enums.TicketStatus
  oldCategoryId?: string | null
  newCategoryId: string
  changedBy: string
  changedAt?: Date | string
  notes?: string | null
}

export type TicketHistoryUpdateInput = {
  oldStatus?: Prisma.NullableEnumTicketStatusFieldUpdateOperationsInput | $Enums.TicketStatus | null
  newStatus?: Prisma.EnumTicketStatusFieldUpdateOperationsInput | $Enums.TicketStatus
  oldCategoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newCategoryId?: Prisma.StringFieldUpdateOperationsInput | string
  changedBy?: Prisma.StringFieldUpdateOperationsInput | string
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ticket?: Prisma.TicketUpdateOneRequiredWithoutHistoryNestedInput
}

export type TicketHistoryUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  ticketId?: Prisma.IntFieldUpdateOperationsInput | number
  oldStatus?: Prisma.NullableEnumTicketStatusFieldUpdateOperationsInput | $Enums.TicketStatus | null
  newStatus?: Prisma.EnumTicketStatusFieldUpdateOperationsInput | $Enums.TicketStatus
  oldCategoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newCategoryId?: Prisma.StringFieldUpdateOperationsInput | string
  changedBy?: Prisma.StringFieldUpdateOperationsInput | string
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TicketHistoryCreateManyInput = {
  id?: number
  ticketId: number
  oldStatus?: $Enums.TicketStatus | null
  newStatus: $Enums.TicketStatus
  oldCategoryId?: string | null
  newCategoryId: string
  changedBy: string
  changedAt?: Date | string
  notes?: string | null
}

export type TicketHistoryUpdateManyMutationInput = {
  oldStatus?: Prisma.NullableEnumTicketStatusFieldUpdateOperationsInput | $Enums.TicketStatus | null
  newStatus?: Prisma.EnumTicketStatusFieldUpdateOperationsInput | $Enums.TicketStatus
  oldCategoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newCategoryId?: Prisma.StringFieldUpdateOperationsInput | string
  changedBy?: Prisma.StringFieldUpdateOperationsInput | string
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TicketHistoryUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  ticketId?: Prisma.IntFieldUpdateOperationsInput | number
  oldStatus?: Prisma.NullableEnumTicketStatusFieldUpdateOperationsInput | $Enums.TicketStatus | null
  newStatus?: Prisma.EnumTicketStatusFieldUpdateOperationsInput | $Enums.TicketStatus
  oldCategoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newCategoryId?: Prisma.StringFieldUpdateOperationsInput | string
  changedBy?: Prisma.StringFieldUpdateOperationsInput | string
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TicketHistoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
  oldStatus?: Prisma.SortOrder
  newStatus?: Prisma.SortOrder
  oldCategoryId?: Prisma.SortOrder
  newCategoryId?: Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  changedAt?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type TicketHistoryAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
}

export type TicketHistoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
  oldStatus?: Prisma.SortOrder
  newStatus?: Prisma.SortOrder
  oldCategoryId?: Prisma.SortOrder
  newCategoryId?: Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  changedAt?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type TicketHistoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
  oldStatus?: Prisma.SortOrder
  newStatus?: Prisma.SortOrder
  oldCategoryId?: Prisma.SortOrder
  newCategoryId?: Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  changedAt?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type TicketHistorySumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
}

export type TicketHistoryListRelationFilter = {
  every?: Prisma.TicketHistoryWhereInput
  some?: Prisma.TicketHistoryWhereInput
  none?: Prisma.TicketHistoryWhereInput
}

export type TicketHistoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NullableEnumTicketStatusFieldUpdateOperationsInput = {
  set?: $Enums.TicketStatus | null
}

export type EnumTicketStatusFieldUpdateOperationsInput = {
  set?: $Enums.TicketStatus
}

export type TicketHistoryCreateNestedManyWithoutTicketInput = {
  create?: Prisma.XOR<Prisma.TicketHistoryCreateWithoutTicketInput, Prisma.TicketHistoryUncheckedCreateWithoutTicketInput> | Prisma.TicketHistoryCreateWithoutTicketInput[] | Prisma.TicketHistoryUncheckedCreateWithoutTicketInput[]
  connectOrCreate?: Prisma.TicketHistoryCreateOrConnectWithoutTicketInput | Prisma.TicketHistoryCreateOrConnectWithoutTicketInput[]
  createMany?: Prisma.TicketHistoryCreateManyTicketInputEnvelope
  connect?: Prisma.TicketHistoryWhereUniqueInput | Prisma.TicketHistoryWhereUniqueInput[]
}

export type TicketHistoryUncheckedCreateNestedManyWithoutTicketInput = {
  create?: Prisma.XOR<Prisma.TicketHistoryCreateWithoutTicketInput, Prisma.TicketHistoryUncheckedCreateWithoutTicketInput> | Prisma.TicketHistoryCreateWithoutTicketInput[] | Prisma.TicketHistoryUncheckedCreateWithoutTicketInput[]
  connectOrCreate?: Prisma.TicketHistoryCreateOrConnectWithoutTicketInput | Prisma.TicketHistoryCreateOrConnectWithoutTicketInput[]
  createMany?: Prisma.TicketHistoryCreateManyTicketInputEnvelope
  connect?: Prisma.TicketHistoryWhereUniqueInput | Prisma.TicketHistoryWhereUniqueInput[]
}

export type TicketHistoryUpdateManyWithoutTicketNestedInput = {
  create?: Prisma.XOR<Prisma.TicketHistoryCreateWithoutTicketInput, Prisma.TicketHistoryUncheckedCreateWithoutTicketInput> | Prisma.TicketHistoryCreateWithoutTicketInput[] | Prisma.TicketHistoryUncheckedCreateWithoutTicketInput[]
  connectOrCreate?: Prisma.TicketHistoryCreateOrConnectWithoutTicketInput | Prisma.TicketHistoryCreateOrConnectWithoutTicketInput[]
  upsert?: Prisma.TicketHistoryUpsertWithWhereUniqueWithoutTicketInput | Prisma.TicketHistoryUpsertWithWhereUniqueWithoutTicketInput[]
  createMany?: Prisma.TicketHistoryCreateManyTicketInputEnvelope
  set?: Prisma.TicketHistoryWhereUniqueInput | Prisma.TicketHistoryWhereUniqueInput[]
  disconnect?: Prisma.TicketHistoryWhereUniqueInput | Prisma.TicketHistoryWhereUniqueInput[]
  delete?: Prisma.TicketHistoryWhereUniqueInput | Prisma.TicketHistoryWhereUniqueInput[]
  connect?: Prisma.TicketHistoryWhereUniqueInput | Prisma.TicketHistoryWhereUniqueInput[]
  update?: Prisma.TicketHistoryUpdateWithWhereUniqueWithoutTicketInput | Prisma.TicketHistoryUpdateWithWhereUniqueWithoutTicketInput[]
  updateMany?: Prisma.TicketHistoryUpdateManyWithWhereWithoutTicketInput | Prisma.TicketHistoryUpdateManyWithWhereWithoutTicketInput[]
  deleteMany?: Prisma.TicketHistoryScalarWhereInput | Prisma.TicketHistoryScalarWhereInput[]
}

export type TicketHistoryUncheckedUpdateManyWithoutTicketNestedInput = {
  create?: Prisma.XOR<Prisma.TicketHistoryCreateWithoutTicketInput, Prisma.TicketHistoryUncheckedCreateWithoutTicketInput> | Prisma.TicketHistoryCreateWithoutTicketInput[] | Prisma.TicketHistoryUncheckedCreateWithoutTicketInput[]
  connectOrCreate?: Prisma.TicketHistoryCreateOrConnectWithoutTicketInput | Prisma.TicketHistoryCreateOrConnectWithoutTicketInput[]
  upsert?: Prisma.TicketHistoryUpsertWithWhereUniqueWithoutTicketInput | Prisma.TicketHistoryUpsertWithWhereUniqueWithoutTicketInput[]
  createMany?: Prisma.TicketHistoryCreateManyTicketInputEnvelope
  set?: Prisma.TicketHistoryWhereUniqueInput | Prisma.TicketHistoryWhereUniqueInput[]
  disconnect?: Prisma.TicketHistoryWhereUniqueInput | Prisma.TicketHistoryWhereUniqueInput[]
  delete?: Prisma.TicketHistoryWhereUniqueInput | Prisma.TicketHistoryWhereUniqueInput[]
  connect?: Prisma.TicketHistoryWhereUniqueInput | Prisma.TicketHistoryWhereUniqueInput[]
  update?: Prisma.TicketHistoryUpdateWithWhereUniqueWithoutTicketInput | Prisma.TicketHistoryUpdateWithWhereUniqueWithoutTicketInput[]
  updateMany?: Prisma.TicketHistoryUpdateManyWithWhereWithoutTicketInput | Prisma.TicketHistoryUpdateManyWithWhereWithoutTicketInput[]
  deleteMany?: Prisma.TicketHistoryScalarWhereInput | Prisma.TicketHistoryScalarWhereInput[]
}

export type TicketHistoryCreateWithoutTicketInput = {
  oldStatus?: $Enums.TicketStatus | null
  newStatus: $Enums.TicketStatus
  oldCategoryId?: string | null
  newCategoryId: string
  changedBy: string
  changedAt?: Date | string
  notes?: string | null
}

export type TicketHistoryUncheckedCreateWithoutTicketInput = {
  id?: number
  oldStatus?: $Enums.TicketStatus | null
  newStatus: $Enums.TicketStatus
  oldCategoryId?: string | null
  newCategoryId: string
  changedBy: string
  changedAt?: Date | string
  notes?: string | null
}

export type TicketHistoryCreateOrConnectWithoutTicketInput = {
  where: Prisma.TicketHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.TicketHistoryCreateWithoutTicketInput, Prisma.TicketHistoryUncheckedCreateWithoutTicketInput>
}

export type TicketHistoryCreateManyTicketInputEnvelope = {
  data: Prisma.TicketHistoryCreateManyTicketInput | Prisma.TicketHistoryCreateManyTicketInput[]
}

export type TicketHistoryUpsertWithWhereUniqueWithoutTicketInput = {
  where: Prisma.TicketHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.TicketHistoryUpdateWithoutTicketInput, Prisma.TicketHistoryUncheckedUpdateWithoutTicketInput>
  create: Prisma.XOR<Prisma.TicketHistoryCreateWithoutTicketInput, Prisma.TicketHistoryUncheckedCreateWithoutTicketInput>
}

export type TicketHistoryUpdateWithWhereUniqueWithoutTicketInput = {
  where: Prisma.TicketHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.TicketHistoryUpdateWithoutTicketInput, Prisma.TicketHistoryUncheckedUpdateWithoutTicketInput>
}

export type TicketHistoryUpdateManyWithWhereWithoutTicketInput = {
  where: Prisma.TicketHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.TicketHistoryUpdateManyMutationInput, Prisma.TicketHistoryUncheckedUpdateManyWithoutTicketInput>
}

export type TicketHistoryScalarWhereInput = {
  AND?: Prisma.TicketHistoryScalarWhereInput | Prisma.TicketHistoryScalarWhereInput[]
  OR?: Prisma.TicketHistoryScalarWhereInput[]
  NOT?: Prisma.TicketHistoryScalarWhereInput | Prisma.TicketHistoryScalarWhereInput[]
  id?: Prisma.IntFilter<"TicketHistory"> | number
  ticketId?: Prisma.IntFilter<"TicketHistory"> | number
  oldStatus?: Prisma.EnumTicketStatusNullableFilter<"TicketHistory"> | $Enums.TicketStatus | null
  newStatus?: Prisma.EnumTicketStatusFilter<"TicketHistory"> | $Enums.TicketStatus
  oldCategoryId?: Prisma.StringNullableFilter<"TicketHistory"> | string | null
  newCategoryId?: Prisma.StringFilter<"TicketHistory"> | string
  changedBy?: Prisma.StringFilter<"TicketHistory"> | string
  changedAt?: Prisma.DateTimeFilter<"TicketHistory"> | Date | string
  notes?: Prisma.StringNullableFilter<"TicketHistory"> | string | null
}

export type TicketHistoryCreateManyTicketInput = {
  id?: number
  oldStatus?: $Enums.TicketStatus | null
  newStatus: $Enums.TicketStatus
  oldCategoryId?: string | null
  newCategoryId: string
  changedBy: string
  changedAt?: Date | string
  notes?: string | null
}

export type TicketHistoryUpdateWithoutTicketInput = {
  oldStatus?: Prisma.NullableEnumTicketStatusFieldUpdateOperationsInput | $Enums.TicketStatus | null
  newStatus?: Prisma.EnumTicketStatusFieldUpdateOperationsInput | $Enums.TicketStatus
  oldCategoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newCategoryId?: Prisma.StringFieldUpdateOperationsInput | string
  changedBy?: Prisma.StringFieldUpdateOperationsInput | string
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TicketHistoryUncheckedUpdateWithoutTicketInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  oldStatus?: Prisma.NullableEnumTicketStatusFieldUpdateOperationsInput | $Enums.TicketStatus | null
  newStatus?: Prisma.EnumTicketStatusFieldUpdateOperationsInput | $Enums.TicketStatus
  oldCategoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newCategoryId?: Prisma.StringFieldUpdateOperationsInput | string
  changedBy?: Prisma.StringFieldUpdateOperationsInput | string
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TicketHistoryUncheckedUpdateManyWithoutTicketInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  oldStatus?: Prisma.NullableEnumTicketStatusFieldUpdateOperationsInput | $Enums.TicketStatus | null
  newStatus?: Prisma.EnumTicketStatusFieldUpdateOperationsInput | $Enums.TicketStatus
  oldCategoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newCategoryId?: Prisma.StringFieldUpdateOperationsInput | string
  changedBy?: Prisma.StringFieldUpdateOperationsInput | string
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type TicketHistorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ticketId?: boolean
  oldStatus?: boolean
  newStatus?: boolean
  oldCategoryId?: boolean
  newCategoryId?: boolean
  changedBy?: boolean
  changedAt?: boolean
  notes?: boolean
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticketHistory"]>

export type TicketHistorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ticketId?: boolean
  oldStatus?: boolean
  newStatus?: boolean
  oldCategoryId?: boolean
  newCategoryId?: boolean
  changedBy?: boolean
  changedAt?: boolean
  notes?: boolean
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticketHistory"]>

export type TicketHistorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ticketId?: boolean
  oldStatus?: boolean
  newStatus?: boolean
  oldCategoryId?: boolean
  newCategoryId?: boolean
  changedBy?: boolean
  changedAt?: boolean
  notes?: boolean
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticketHistory"]>

export type TicketHistorySelectScalar = {
  id?: boolean
  ticketId?: boolean
  oldStatus?: boolean
  newStatus?: boolean
  oldCategoryId?: boolean
  newCategoryId?: boolean
  changedBy?: boolean
  changedAt?: boolean
  notes?: boolean
}

export type TicketHistoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "ticketId" | "oldStatus" | "newStatus" | "oldCategoryId" | "newCategoryId" | "changedBy" | "changedAt" | "notes", ExtArgs["result"]["ticketHistory"]>
export type TicketHistoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
}
export type TicketHistoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
}
export type TicketHistoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
}

export type $TicketHistoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TicketHistory"
  objects: {
    ticket: Prisma.$TicketPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    ticketId: number
    oldStatus: $Enums.TicketStatus | null
    newStatus: $Enums.TicketStatus
    oldCategoryId: string | null
    newCategoryId: string
    changedBy: string
    changedAt: Date
    notes: string | null
  }, ExtArgs["result"]["ticketHistory"]>
  composites: {}
}

export type TicketHistoryGetPayload<S extends boolean | null | undefined | TicketHistoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TicketHistoryPayload, S>

export type TicketHistoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TicketHistoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TicketHistoryCountAggregateInputType | true
  }

export interface TicketHistoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TicketHistory'], meta: { name: 'TicketHistory' } }
  /**
   * Find zero or one TicketHistory that matches the filter.
   * @param {TicketHistoryFindUniqueArgs} args - Arguments to find a TicketHistory
   * @example
   * // Get one TicketHistory
   * const ticketHistory = await prisma.ticketHistory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TicketHistoryFindUniqueArgs>(args: Prisma.SelectSubset<T, TicketHistoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TicketHistoryClient<runtime.Types.Result.GetResult<Prisma.$TicketHistoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TicketHistory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TicketHistoryFindUniqueOrThrowArgs} args - Arguments to find a TicketHistory
   * @example
   * // Get one TicketHistory
   * const ticketHistory = await prisma.ticketHistory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TicketHistoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TicketHistoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketHistoryClient<runtime.Types.Result.GetResult<Prisma.$TicketHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TicketHistory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketHistoryFindFirstArgs} args - Arguments to find a TicketHistory
   * @example
   * // Get one TicketHistory
   * const ticketHistory = await prisma.ticketHistory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TicketHistoryFindFirstArgs>(args?: Prisma.SelectSubset<T, TicketHistoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__TicketHistoryClient<runtime.Types.Result.GetResult<Prisma.$TicketHistoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TicketHistory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketHistoryFindFirstOrThrowArgs} args - Arguments to find a TicketHistory
   * @example
   * // Get one TicketHistory
   * const ticketHistory = await prisma.ticketHistory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TicketHistoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TicketHistoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketHistoryClient<runtime.Types.Result.GetResult<Prisma.$TicketHistoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TicketHistories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketHistoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TicketHistories
   * const ticketHistories = await prisma.ticketHistory.findMany()
   * 
   * // Get first 10 TicketHistories
   * const ticketHistories = await prisma.ticketHistory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ticketHistoryWithIdOnly = await prisma.ticketHistory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TicketHistoryFindManyArgs>(args?: Prisma.SelectSubset<T, TicketHistoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TicketHistory.
   * @param {TicketHistoryCreateArgs} args - Arguments to create a TicketHistory.
   * @example
   * // Create one TicketHistory
   * const TicketHistory = await prisma.ticketHistory.create({
   *   data: {
   *     // ... data to create a TicketHistory
   *   }
   * })
   * 
   */
  create<T extends TicketHistoryCreateArgs>(args: Prisma.SelectSubset<T, TicketHistoryCreateArgs<ExtArgs>>): Prisma.Prisma__TicketHistoryClient<runtime.Types.Result.GetResult<Prisma.$TicketHistoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TicketHistories.
   * @param {TicketHistoryCreateManyArgs} args - Arguments to create many TicketHistories.
   * @example
   * // Create many TicketHistories
   * const ticketHistory = await prisma.ticketHistory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TicketHistoryCreateManyArgs>(args?: Prisma.SelectSubset<T, TicketHistoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TicketHistories and returns the data saved in the database.
   * @param {TicketHistoryCreateManyAndReturnArgs} args - Arguments to create many TicketHistories.
   * @example
   * // Create many TicketHistories
   * const ticketHistory = await prisma.ticketHistory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TicketHistories and only return the `id`
   * const ticketHistoryWithIdOnly = await prisma.ticketHistory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TicketHistoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TicketHistoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketHistoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TicketHistory.
   * @param {TicketHistoryDeleteArgs} args - Arguments to delete one TicketHistory.
   * @example
   * // Delete one TicketHistory
   * const TicketHistory = await prisma.ticketHistory.delete({
   *   where: {
   *     // ... filter to delete one TicketHistory
   *   }
   * })
   * 
   */
  delete<T extends TicketHistoryDeleteArgs>(args: Prisma.SelectSubset<T, TicketHistoryDeleteArgs<ExtArgs>>): Prisma.Prisma__TicketHistoryClient<runtime.Types.Result.GetResult<Prisma.$TicketHistoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TicketHistory.
   * @param {TicketHistoryUpdateArgs} args - Arguments to update one TicketHistory.
   * @example
   * // Update one TicketHistory
   * const ticketHistory = await prisma.ticketHistory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TicketHistoryUpdateArgs>(args: Prisma.SelectSubset<T, TicketHistoryUpdateArgs<ExtArgs>>): Prisma.Prisma__TicketHistoryClient<runtime.Types.Result.GetResult<Prisma.$TicketHistoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TicketHistories.
   * @param {TicketHistoryDeleteManyArgs} args - Arguments to filter TicketHistories to delete.
   * @example
   * // Delete a few TicketHistories
   * const { count } = await prisma.ticketHistory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TicketHistoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, TicketHistoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TicketHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketHistoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TicketHistories
   * const ticketHistory = await prisma.ticketHistory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TicketHistoryUpdateManyArgs>(args: Prisma.SelectSubset<T, TicketHistoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TicketHistories and returns the data updated in the database.
   * @param {TicketHistoryUpdateManyAndReturnArgs} args - Arguments to update many TicketHistories.
   * @example
   * // Update many TicketHistories
   * const ticketHistory = await prisma.ticketHistory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TicketHistories and only return the `id`
   * const ticketHistoryWithIdOnly = await prisma.ticketHistory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TicketHistoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TicketHistoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketHistoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TicketHistory.
   * @param {TicketHistoryUpsertArgs} args - Arguments to update or create a TicketHistory.
   * @example
   * // Update or create a TicketHistory
   * const ticketHistory = await prisma.ticketHistory.upsert({
   *   create: {
   *     // ... data to create a TicketHistory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TicketHistory we want to update
   *   }
   * })
   */
  upsert<T extends TicketHistoryUpsertArgs>(args: Prisma.SelectSubset<T, TicketHistoryUpsertArgs<ExtArgs>>): Prisma.Prisma__TicketHistoryClient<runtime.Types.Result.GetResult<Prisma.$TicketHistoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TicketHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketHistoryCountArgs} args - Arguments to filter TicketHistories to count.
   * @example
   * // Count the number of TicketHistories
   * const count = await prisma.ticketHistory.count({
   *   where: {
   *     // ... the filter for the TicketHistories we want to count
   *   }
   * })
  **/
  count<T extends TicketHistoryCountArgs>(
    args?: Prisma.Subset<T, TicketHistoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TicketHistoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TicketHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketHistoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TicketHistoryAggregateArgs>(args: Prisma.Subset<T, TicketHistoryAggregateArgs>): Prisma.PrismaPromise<GetTicketHistoryAggregateType<T>>

  /**
   * Group by TicketHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketHistoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TicketHistoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TicketHistoryGroupByArgs['orderBy'] }
      : { orderBy?: TicketHistoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TicketHistoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTicketHistoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TicketHistory model
 */
readonly fields: TicketHistoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TicketHistory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TicketHistoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  ticket<T extends Prisma.TicketDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TicketDefaultArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TicketHistory model
 */
export interface TicketHistoryFieldRefs {
  readonly id: Prisma.FieldRef<"TicketHistory", 'Int'>
  readonly ticketId: Prisma.FieldRef<"TicketHistory", 'Int'>
  readonly oldStatus: Prisma.FieldRef<"TicketHistory", 'TicketStatus'>
  readonly newStatus: Prisma.FieldRef<"TicketHistory", 'TicketStatus'>
  readonly oldCategoryId: Prisma.FieldRef<"TicketHistory", 'String'>
  readonly newCategoryId: Prisma.FieldRef<"TicketHistory", 'String'>
  readonly changedBy: Prisma.FieldRef<"TicketHistory", 'String'>
  readonly changedAt: Prisma.FieldRef<"TicketHistory", 'DateTime'>
  readonly notes: Prisma.FieldRef<"TicketHistory", 'String'>
}
    

// Custom InputTypes
/**
 * TicketHistory findUnique
 */
export type TicketHistoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketHistory
   */
  select?: Prisma.TicketHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketHistory
   */
  omit?: Prisma.TicketHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketHistoryInclude<ExtArgs> | null
  /**
   * Filter, which TicketHistory to fetch.
   */
  where: Prisma.TicketHistoryWhereUniqueInput
}

/**
 * TicketHistory findUniqueOrThrow
 */
export type TicketHistoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketHistory
   */
  select?: Prisma.TicketHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketHistory
   */
  omit?: Prisma.TicketHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketHistoryInclude<ExtArgs> | null
  /**
   * Filter, which TicketHistory to fetch.
   */
  where: Prisma.TicketHistoryWhereUniqueInput
}

/**
 * TicketHistory findFirst
 */
export type TicketHistoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketHistory
   */
  select?: Prisma.TicketHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketHistory
   */
  omit?: Prisma.TicketHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketHistoryInclude<ExtArgs> | null
  /**
   * Filter, which TicketHistory to fetch.
   */
  where?: Prisma.TicketHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketHistories to fetch.
   */
  orderBy?: Prisma.TicketHistoryOrderByWithRelationInput | Prisma.TicketHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TicketHistories.
   */
  cursor?: Prisma.TicketHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TicketHistories.
   */
  distinct?: Prisma.TicketHistoryScalarFieldEnum | Prisma.TicketHistoryScalarFieldEnum[]
}

/**
 * TicketHistory findFirstOrThrow
 */
export type TicketHistoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketHistory
   */
  select?: Prisma.TicketHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketHistory
   */
  omit?: Prisma.TicketHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketHistoryInclude<ExtArgs> | null
  /**
   * Filter, which TicketHistory to fetch.
   */
  where?: Prisma.TicketHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketHistories to fetch.
   */
  orderBy?: Prisma.TicketHistoryOrderByWithRelationInput | Prisma.TicketHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TicketHistories.
   */
  cursor?: Prisma.TicketHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TicketHistories.
   */
  distinct?: Prisma.TicketHistoryScalarFieldEnum | Prisma.TicketHistoryScalarFieldEnum[]
}

/**
 * TicketHistory findMany
 */
export type TicketHistoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketHistory
   */
  select?: Prisma.TicketHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketHistory
   */
  omit?: Prisma.TicketHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketHistoryInclude<ExtArgs> | null
  /**
   * Filter, which TicketHistories to fetch.
   */
  where?: Prisma.TicketHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketHistories to fetch.
   */
  orderBy?: Prisma.TicketHistoryOrderByWithRelationInput | Prisma.TicketHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TicketHistories.
   */
  cursor?: Prisma.TicketHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketHistories.
   */
  skip?: number
  distinct?: Prisma.TicketHistoryScalarFieldEnum | Prisma.TicketHistoryScalarFieldEnum[]
}

/**
 * TicketHistory create
 */
export type TicketHistoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketHistory
   */
  select?: Prisma.TicketHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketHistory
   */
  omit?: Prisma.TicketHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketHistoryInclude<ExtArgs> | null
  /**
   * The data needed to create a TicketHistory.
   */
  data: Prisma.XOR<Prisma.TicketHistoryCreateInput, Prisma.TicketHistoryUncheckedCreateInput>
}

/**
 * TicketHistory createMany
 */
export type TicketHistoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TicketHistories.
   */
  data: Prisma.TicketHistoryCreateManyInput | Prisma.TicketHistoryCreateManyInput[]
}

/**
 * TicketHistory createManyAndReturn
 */
export type TicketHistoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketHistory
   */
  select?: Prisma.TicketHistorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TicketHistory
   */
  omit?: Prisma.TicketHistoryOmit<ExtArgs> | null
  /**
   * The data used to create many TicketHistories.
   */
  data: Prisma.TicketHistoryCreateManyInput | Prisma.TicketHistoryCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketHistoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TicketHistory update
 */
export type TicketHistoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketHistory
   */
  select?: Prisma.TicketHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketHistory
   */
  omit?: Prisma.TicketHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketHistoryInclude<ExtArgs> | null
  /**
   * The data needed to update a TicketHistory.
   */
  data: Prisma.XOR<Prisma.TicketHistoryUpdateInput, Prisma.TicketHistoryUncheckedUpdateInput>
  /**
   * Choose, which TicketHistory to update.
   */
  where: Prisma.TicketHistoryWhereUniqueInput
}

/**
 * TicketHistory updateMany
 */
export type TicketHistoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TicketHistories.
   */
  data: Prisma.XOR<Prisma.TicketHistoryUpdateManyMutationInput, Prisma.TicketHistoryUncheckedUpdateManyInput>
  /**
   * Filter which TicketHistories to update
   */
  where?: Prisma.TicketHistoryWhereInput
  /**
   * Limit how many TicketHistories to update.
   */
  limit?: number
}

/**
 * TicketHistory updateManyAndReturn
 */
export type TicketHistoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketHistory
   */
  select?: Prisma.TicketHistorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TicketHistory
   */
  omit?: Prisma.TicketHistoryOmit<ExtArgs> | null
  /**
   * The data used to update TicketHistories.
   */
  data: Prisma.XOR<Prisma.TicketHistoryUpdateManyMutationInput, Prisma.TicketHistoryUncheckedUpdateManyInput>
  /**
   * Filter which TicketHistories to update
   */
  where?: Prisma.TicketHistoryWhereInput
  /**
   * Limit how many TicketHistories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketHistoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TicketHistory upsert
 */
export type TicketHistoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketHistory
   */
  select?: Prisma.TicketHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketHistory
   */
  omit?: Prisma.TicketHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketHistoryInclude<ExtArgs> | null
  /**
   * The filter to search for the TicketHistory to update in case it exists.
   */
  where: Prisma.TicketHistoryWhereUniqueInput
  /**
   * In case the TicketHistory found by the `where` argument doesn't exist, create a new TicketHistory with this data.
   */
  create: Prisma.XOR<Prisma.TicketHistoryCreateInput, Prisma.TicketHistoryUncheckedCreateInput>
  /**
   * In case the TicketHistory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TicketHistoryUpdateInput, Prisma.TicketHistoryUncheckedUpdateInput>
}

/**
 * TicketHistory delete
 */
export type TicketHistoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketHistory
   */
  select?: Prisma.TicketHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketHistory
   */
  omit?: Prisma.TicketHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketHistoryInclude<ExtArgs> | null
  /**
   * Filter which TicketHistory to delete.
   */
  where: Prisma.TicketHistoryWhereUniqueInput
}

/**
 * TicketHistory deleteMany
 */
export type TicketHistoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TicketHistories to delete
   */
  where?: Prisma.TicketHistoryWhereInput
  /**
   * Limit how many TicketHistories to delete.
   */
  limit?: number
}

/**
 * TicketHistory without action
 */
export type TicketHistoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketHistory
   */
  select?: Prisma.TicketHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketHistory
   */
  omit?: Prisma.TicketHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketHistoryInclude<ExtArgs> | null
}
